# -*- coding: utf-8 -*-
"""Rebuild the complete research package: bibliography, CSV exports, figures, 4 workbooks, 5 PDFs, README.
Usage:  python _build/build_all.py
Requires: reportlab, openpyxl, matplotlib, fontTools, PyMuPDF (for the final page-count check)."""
import csv, json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import (ROOT, REPORTS, FIGS, CORE, OTHER, EXTRA, J, IDEAS, ACADEMIC, EXPERIMENTS, load_refs, short_author,
                    apa_authors, ref_plain, idea_table_md, ideas_ranked, idea_score, md_table)
import figures
import figures_aftertax
import build_excel
from render_pdf import build_pdf


def rd(rel):
    return open(os.path.join(ROOT, rel), encoding="utf-8").read()


def wr(rel, text):
    p = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "w", encoding="utf-8", newline="\n").write(text)
    return p


def after_heading(md, heading_prefix, insert):
    out, done = [], False
    for ln in md.splitlines():
        out.append(ln)
        if not done and ln.strip().startswith(heading_prefix):
            out += ["", insert, ""]; done = True
    if not done:
        raise ValueError(f"heading not found: {heading_prefix}")
    return "\n".join(out)


def trunc(s, n=300):
    s = (s or "").strip()
    return s if len(s) <= n else s[: n - 3].rsplit(" ", 1)[0] + "..."


# ----------------------------------------------------------------- bibliography outputs
def bib_escape(s):
    return s.replace("\\", "\\\\").replace("&", "\\&").replace("%", "\\%").replace("_", "\\_").replace("#", "\\#")


def write_bibliography(refs):
    entries = []
    for r in sorted(refs.values(), key=lambda r: (r["authors"].lower(), r["year"])):
        t = r["tier"]
        typ = {"Book": "book", "WP": "unpublished", "Industry": "techreport", "ML venue": "inproceedings"}.get(t, "article")
        f = {"author": " and ".join(a.strip() for a in r["authors"].split(";") if a.strip()), "title": "{" + r["title"] + "}",
             "year": str(r["year"])}
        if typ == "article":
            f["journal"] = r["venue"]
        elif typ == "inproceedings":
            f["booktitle"] = r["venue"]
        elif typ == "book":
            f["publisher"] = r["venue"]
        else:
            f["note"] = r["venue"]
        if r.get("doi"):
            f["doi"] = r["doi"]
        if r.get("url"):
            f["url"] = r["url"]
        body = ",\n".join(f"  {k} = {{{bib_escape(v) if k not in ('url', 'doi', 'title') else v}}}" for k, v in f.items())
        entries.append(f"@{typ}{{{r['id']},\n{body}\n}}")
    wr("08_References/references.bib", "% Generated by _build/build_all.py. Keys = project paper IDs.\n\n" + "\n\n".join(entries) + "\n")

    lines = ["# Bibliography (formatted)", "",
             f"{len(refs)} entries. Format: APA-like. DOI shown where verified (see crossref_verification.csv).", ""]
    for r in sorted(refs.values(), key=lambda r: (r["authors"].lower(), r["year"])):
        lines.append(f"- **[{r['id']}]** {ref_plain(r)}")
    wr("08_References/references_formatted.md", "\n".join(lines) + "\n")

    with open(os.path.join(ROOT, "08_References", "crossref_verification.csv"), "w", newline="", encoding="utf-8-sig") as fh:
        w = csv.writer(fh)
        w.writerow(["id", "authors", "year", "title", "venue", "tier", "doi_used", "doi_status", "crossref_status",
                    "crossref_doi", "crossref_title", "crossref_journal"])
        for r in sorted(refs.values(), key=lambda r: r["id"]):
            w.writerow([r["id"], r["authors"], r["year"], r["title"], r["venue"], r["tier"], r.get("doi", ""), r["doi_status"],
                        r["crossref_status"], r["crossref_doi"], r["crossref_title"], r["crossref_journal"]])

    n = len(refs)
    with_doi = sum(1 for r in refs.values() if r.get("doi"))
    crossref_ok = sum(1 for r in refs.values() if r.get("doi") and ("Crossref match" in r["doi_status"] or "Crossref-confirmed" in r["doi_status"]))
    by_status = {}
    for r in refs.values():
        by_status[r["doi_status"]] = by_status.get(r["doi_status"], 0) + 1
    summ = ["# Citation Verification Summary", "",
            "Every bibliographic entry was checked against the Crossref REST API (title + first author query; best match scored by title "
            "similarity, author match, journal container and year). Raw responses and the script are in `crossref_raw/`.", "",
            f"- Entries in bibliography: **{n}**",
            f"- Entries with a DOI: **{with_doi}**",
            f"- DOIs matched or confirmed via Crossref: **{crossref_ok}**", "", "| DOI status | Entries |", "|---|---|"]
    summ += [f"| {k} | {v} |" for k, v in sorted(by_status.items(), key=lambda x: -x[1])]
    summ += ["", "**Caveats.** Conference papers (NeurIPS/ICML), books, some surveys and working papers have no Crossref DOI. "
             "Working-paper publication status can change; re-check before submission. Items flagged `[verify]` in the documents "
             "are details not confirmed from accessible full text."]
    wr("08_References/Citation_Verification_Summary.md", "\n".join(summ) + "\n")
    return dict(n=n, with_doi=with_doi, crossref_ok=crossref_ok)


def write_csvs(refs):
    with open(os.path.join(ROOT, "01_Literature_Review", "literature_matrix.csv"), "w", newline="", encoding="utf-8-sig") as fh:
        keys = ["id", "authors", "year", "title", "venue", "tier", "category", "relevance", "core", "doi", "url", "rq", "data", "universe",
                "freq", "features", "ml", "signal", "portfolio", "benchmark", "metrics", "period", "tcost", "turnover", "risk", "result",
                "contribution", "limitation", "not_solved", "gap", "extension", "doi_status"]
        w = csv.DictWriter(fh, fieldnames=keys, extrasaction="ignore"); w.writeheader()
        for r in sorted(refs.values(), key=lambda r: (not r.get("core"), -r["relevance"], r["id"])):
            w.writerow(r)
    with open(os.path.join(ROOT, "02_Journal_Strategy", "journal_analysis.csv"), "w", newline="", encoding="utf-8-sig") as fh:
        w = csv.DictWriter(fh, fieldnames=list(J[0].keys())); w.writeheader(); [w.writerow(j) for j in J]
    with open(os.path.join(ROOT, "04_Paper_Concepts", "idea_matrix.csv"), "w", newline="", encoding="utf-8-sig") as fh:
        keys = list(IDEAS[0].keys()) + ["academic", "overall_score"]
        w = csv.DictWriter(fh, fieldnames=keys); w.writeheader()
        for i in ideas_ranked():
            w.writerow({**i, "academic": ACADEMIC[i["id"]], "overall_score": idea_score(i)})
    with open(os.path.join(ROOT, "07_Experimental_Framework", "experiment_register.csv"), "w", newline="", encoding="utf-8-sig") as fh:
        w = csv.writer(fh)
        w.writerow(["id", "phase", "block", "experiment", "hypothesis", "model", "dataset", "benchmark", "metrics", "test",
                    "expected_outcome_hypothesis", "priority", "status"])
        for e in EXPERIMENTS:
            w.writerow(list(e) + ["Not started"])
    md = rd("07_Experimental_Framework/Experimental_Framework.md")
    m = re.search(r"```yaml\n(.*?)```", md, flags=re.S)
    wr("07_Experimental_Framework/experiment_config.yaml",
       "# Proposed baseline configuration (extracted from Experimental_Framework.md). Not yet executed.\n" + m.group(1))
    oa = json.load(open(os.path.join(ROOT, "02_Journal_Strategy", "openalex_journals_raw.json"), encoding="utf-8"))
    with open(os.path.join(ROOT, "02_Journal_Strategy", "openalex_metrics_sep2026.csv"), "w", newline="", encoding="utf-8-sig") as fh:
        w = csv.DictWriter(fh, fieldnames=["query", "name", "issn", "publisher", "works", "cites", "two_yr_mean", "h", "error"])
        w.writeheader(); [w.writerow(o) for o in oa]


# ----------------------------------------------------------------- appendices
def appendix_core_matrix(refs):
    rows = []
    for r in sorted([x for x in refs.values() if x.get("core")], key=lambda r: (-r["relevance"], r["year"])):
        rows.append([f"@{r['id']}", trunc(r["venue"], 60), trunc(f"{r.get('data', '')}; {r.get('universe', '')}", 150),
                     trunc(f"ML: {r.get('ml', '')} | Portfolio: {r.get('portfolio', '')}", 190), trunc(r.get("tcost", ""), 110),
                     trunc(r.get("result", ""), 260), trunc(r.get("not_solved", ""), 170)])
    return ("# Appendix A. Core Literature Matrix (condensed)\n\nFull fields for every paper are in Workbook 1. "
            "Text is truncated here for layout.\n\n" +
            md_table(["Paper", "Venue", "Data / universe", "Method", "Transaction costs", "Main result", "Not solved"], rows))


def appendix_universe(refs):
    rows = []
    for r in sorted(refs.values(), key=lambda r: (r["category"], -r["year"], r["id"])):
        rows.append([r["id"], f"@{r['id']}", trunc(r["title"], 90), trunc(r["venue"], 55), r["category"], r["relevance"]])
    return (f"# Appendix B. Literature Universe ({len(refs)} entries)\n\nSorted by strand and year. Relevance: 1-5 (team judgement).\n\n"
            + md_table(["ID", "Citation", "Title", "Venue", "Strand", "Rel."], rows))


def appendix_journals():
    rows = [[j["journal"], trunc(j["scope"], 140), trunc(j["methodology"], 110), trunc(j["empirical"], 110), trunc(j["theory"], 80),
             trunc(j["note"], 120)] for j in J]
    return "# Appendix. Journal Profiles\n\n" + md_table(["Journal", "Scope", "Typical methodology", "Empirical expectations", "Theory", "Notes"], rows)


def appendix_experiments():
    rows = [[e[0], e[2], e[3], trunc(e[4], 150), trunc(e[9], 70), trunc(e[10], 90), e[11]] for e in EXPERIMENTS]
    return ("# Appendix. Experiment Register\n\nExpected outcomes are pre-registered hypotheses, not results. Status tracking in Workbook 4.\n\n"
            + md_table(["ID", "Block", "Experiment", "Hypothesis", "Test", "Expected (hypothesis)", "Priority"], rows))


# ----------------------------------------------------------------- main
def main():
    refs = load_refs()
    stats = write_bibliography(refs)
    write_csvs(refs)
    figs = figures.build_all()
    # After-tax and adaptive figures read alphacomb/outputs/*.csv. Any figure whose source file is
    # missing is skipped, not drawn from placeholders, so a partial pipeline run shows as a gap.
    figs += figures_aftertax.build_all()
    wbs = build_excel.build_all(refs)

    pdf = {k: os.path.join(REPORTS, v) for k, v in {
        "p1": "PDF1_Comprehensive_Literature_Review.pdf", "p2": "PDF2_Journal_Strategy.pdf",
        "p3": "PDF3_Research_Gap_and_Opportunity_Report.pdf", "p4": "PDF4_Proposed_Research_Design.pdf",
        "p5": "PDF5_Final_Research_Blueprint.pdf"}.items()}

    file_rows = [
        ["PDF 1", "09_Reports/PDF1_Comprehensive_Literature_Review.pdf", "Executive summary, literature evolution, key papers, methods, findings, gaps, BlackRock AIM analysis, matrix appendices"],
        ["PDF 2", "09_Reports/PDF2_Journal_Strategy.pdf", "Journal tiers, comparison, fit, expectations, ranking, submission strategy, reviewer checklist"],
        ["PDF 3", "09_Reports/PDF3_Research_Gap_and_Opportunity_Report.pdf", "Existing approaches, weaknesses, gaps, pipelines A-F, prior-art tracker, 15 ideas, 5 concepts"],
        ["PDF 4", "09_Reports/PDF4_Proposed_Research_Design.pdf", "Research question, hypotheses, architecture, data, ML/portfolio methods, benchmarks, experiments, statistics"],
        ["PDF 5", "09_Reports/PDF5_Final_Research_Blueprint.pdf", "Consolidated working blueprint (overview + design + framework + checklist + roadmap)"],
        ["Workbook 1", "09_Reports/Workbook1_Literature_Database.xlsx", f"{stats['n']} entries; summary formulas; closest prior art; legend"],
        ["Workbook 2", "09_Reports/Workbook2_Journal_Analysis.xlsx", "Journal analysis with priority formulas, role formatting, metrics note"],
        ["Workbook 3", "09_Reports/Workbook3_Research_Idea_Matrix.xlsx", "15 ideas; editable weights; score and rank formulas; concept selection"],
        ["Workbook 4", "09_Reports/Workbook4_Experiment_Matrix.xlsx", "Experiment register with status dropdowns, progress summary, factorial contrasts, Gantt, checklist tracker"],
    ]
    tokens = {"IDEA_TABLE": idea_table_md(), "FILE_INDEX": md_table(["Deliverable", "Path", "Contents"], file_rows)}

    blurb = lambda s: s
    common_blurb = ("This report is part of a pre-empirical research proposal. It distinguishes verified evidence, research inference, "
                    "proposed design choices and hypotheses. No backtest results are reported; expected outcomes are hypotheses.")

    lit = rd("01_Literature_Review/Literature_Review.md")
    lit = after_heading(lit, "## 2. Evolution of the Literature",
                        "{{FIG:fig_literature_timeline.png|Figure 1. Composition of the assembled literature universe by period and strand (counts from Workbook 1).}}")
    lit = after_heading(lit, "## 6. Prediction Is Not Investment Value",
                        "{{FIG:fig_prediction_to_value.png|Figure 2. Conceptual chain from forecast quality to net investment value; each link is measured in the proposed design.}}")
    c1 = build_pdf(pdf["p1"], dict(kicker="Report 1 of 5 | Literature", title="Comprehensive Literature Review",
                                   subtitle="Machine learning for alpha signal combination and portfolio construction: what is known, what is solved, and what remains open",
                                   blurb=common_blurb, short="PDF 1 - Comprehensive Literature Review", report_no="Report 1 of 5"),
                   [("md", lit), ("break", None), ("md", appendix_core_matrix(refs)), ("break", None), ("md", appendix_universe(refs))], refs, tokens)

    js = rd("02_Journal_Strategy/Journal_Strategy.md")
    js = after_heading(js, "## 2. Journal Comparison",
                       "{{FIG:fig_journal_map.png|Figure 1. Project fit score (team assessment) by journal, coloured by venue class, with recommended role. OpenAlex metrics and details in Workbook 2.}}")
    c2 = build_pdf(pdf["p2"], dict(kicker="Report 2 of 5 | Journals", title="Journal Strategy",
                                   subtitle="Journal tiers, fit, reviewer expectations, target ranking and submission strategy",
                                   blurb=common_blurb, short="PDF 2 - Journal Strategy", report_no="Report 2 of 5"),
                   [("md", js), ("break", None), ("md", rd("07_Experimental_Framework/Reviewer_Proof_Checklist.md")), ("break", None),
                    ("md", appendix_journals())], refs, tokens)

    gaps = rd("03_Research_Gaps/Research_Gaps_and_Opportunities.md")
    gaps = after_heading(gaps, "## 7. Opportunity Matrix",
                         "{{FIG:fig_opportunity_matrix.png|Figure 1. Opportunity matrix of the 15 candidate ideas (scores are team judgements; see Workbook 3).}}")
    c3 = build_pdf(pdf["p3"], dict(kicker="Report 3 of 5 | Gaps", title="Research Gap and Opportunity Report",
                                   subtitle="Existing approaches, weaknesses, open questions, closest prior art, 15 ideas and 5 paper concepts",
                                   blurb=common_blurb, short="PDF 3 - Research Gap & Opportunity Report", report_no="Report 3 of 5"),
                   [("md", gaps), ("break", None), ("md", rd("03_Research_Gaps/Closest_Prior_Art_Tracker.md")), ("break", None),
                    ("md", rd("04_Paper_Concepts/Research_Ideas_and_Paper_Concepts.md"))], refs, tokens)

    design = rd("05_Selected_Research_Design/Selected_Research_Design.md")
    design = after_heading(design, "## 3. Architecture",
                           "{{FIG:fig_pipeline.png|Figure 1. End-to-end empirical pipeline.}}\n\n{{FIG:fig_factorial_design.png|Figure 2. The 16-cell factorial design (experiment IDs from Workbook 4).}}")
    c4 = build_pdf(pdf["p4"], dict(kicker="Report 4 of 5 | Design", title="Proposed Research Design",
                                   subtitle="Where does machine-learning alpha come from after trading costs? Hypotheses, architecture, data, methods, benchmarks, experiments and statistics",
                                   blurb=common_blurb, short="PDF 4 - Proposed Research Design", report_no="Report 4 of 5"),
                   [("md", design), ("break", None), ("md", rd("06_Data_Strategy/Data_Strategy.md")), ("break", None),
                    ("md", rd("07_Experimental_Framework/Experimental_Framework.md")), ("break", None), ("md", appendix_experiments())], refs, tokens)

    overview = rd("05_Selected_Research_Design/Final_Blueprint_Overview.md")
    roadmap = after_heading(rd("07_Experimental_Framework/Research_Roadmap.md"), "# Research Roadmap",
                            "{{FIG:fig_roadmap.png|Figure. Implementation roadmap with go/no-go gates (planning estimates).}}")
    c5 = build_pdf(pdf["p5"], dict(kicker="Report 5 of 5 | Blueprint", title="Final Research Blueprint",
                                   subtitle="Consolidated working blueprint for the paper: question, contribution, design, data, experiments, inference, journals, checklist and roadmap",
                                   blurb=common_blurb, short="PDF 5 - Final Research Blueprint", report_no="Report 5 of 5"),
                   [("md", overview.replace("# Final Research Blueprint: Overview", "# Part I. Blueprint Overview")), ("break", None),
                    ("md", design.replace("# Proposed Research Design:", "# Part II. Research Design:")), ("break", None),
                    ("md", rd("07_Experimental_Framework/Experimental_Framework.md").replace("# Experimental Framework", "# Part III. Experimental Framework")),
                    ("break", None), ("md", rd("07_Experimental_Framework/Reviewer_Proof_Checklist.md").replace("# Reviewer-Proof Checklist", "# Part IV. Reviewer-Proof Checklist")),
                    ("break", None), ("md", roadmap.replace("# Research Roadmap", "# Part V. Research Roadmap"))], refs, tokens)

    warns = set().union(c1.warnings, c2.warnings, c3.warnings, c4.warnings, c5.warnings)

    # README
    verify_count = sum(len(re.findall(r"\[verify", open(os.path.join(dp, f), encoding="utf-8").read()))
                       for dp, _, fs in os.walk(ROOT) for f in fs if f.endswith((".md", ".py")) and "_build" in dp or f.endswith(".md"))
    readme = f"""# ML Alpha Signal Combination Research Package

**Topic:** Machine Learning for Alpha Signal Combination and Portfolio Construction
**Status:** Pre-empirical research proposal (September 2026). No backtests have been run; expected outcomes are hypotheses.

## Selected paper (proposed)

*Where Does Machine-Learning Alpha Come From After Trading Costs? Nonlinearity, State Dependence and Cost-Aware Learning in Signal Combination.*
A controlled 2x2x2x2 factorial attribution of net-of-cost value to nonlinearity, state-dependent weights, a cost-aware objective and forecast
uncertainty, with data-snooping-robust inference and economic mechanism tests. Primary targets: JFQA, Management Science; stretch: RFS.

## Deliverables

{md_table(["Deliverable", "Path", "Contents"], [[a, f"[{b}]({b.replace(' ', '%20')})", c] for a, b, c in file_rows])}

## Folder structure

| Folder | Contents |
|---|---|
| [01_Literature_Review](01_Literature_Review) | Literature review (Markdown source), literature matrix CSV |
| [02_Journal_Strategy](02_Journal_Strategy) | Journal strategy, journal analysis CSV, OpenAlex metrics (raw JSON, CSV, pull script) |
| [03_Research_Gaps](03_Research_Gaps) | Gap and opportunity report; **living closest-prior-art tracker** |
| [04_Paper_Concepts](04_Paper_Concepts) | 15 ideas, 5 full concepts, selection; idea matrix CSV |
| [05_Selected_Research_Design](05_Selected_Research_Design) | Selected design (incl. contribution statement and closest-paper tables); blueprint overview |
| [06_Data_Strategy](06_Data_Strategy) | Data sources, bias register, point-in-time rules |
| [07_Experimental_Framework](07_Experimental_Framework) | Implementation spec, YAML config, experiment register, reviewer-proof checklist, roadmap |
| [08_References](08_References) | BibTeX, formatted bibliography, Crossref verification CSV + raw responses + script |
| [09_Reports](09_Reports) | 5 PDFs, 4 Excel workbooks, figures |
| [_build](_build) | Single source of truth (data modules) and build scripts |

## Evidence conventions

- **Verified**: from publisher pages, abstracts, authors' repositories, Crossref/OpenAlex APIs.
- **[inference]**: research-team synthesis. **[verify]**: not confirmed from accessible full text ({verify_count} flags across sources); check before citing.
- **Proposed**: our design choice. **Hypothesis**: to be tested; never a result.

## Verification statistics

- Bibliography entries: {stats['n']}; with DOI: {stats['with_doi']}; DOI matched/confirmed via Crossref: {stats['crossref_ok']}.
- Journal Impact Factors (Clarivate) were **not** verifiable and are not reported; OpenAlex 2-year mean citedness is reported instead.

## Rebuild

```
python _build/build_all.py
```
Requires Python 3.12 with reportlab, openpyxl, matplotlib, fontTools, PyMuPDF; fonts Georgia/Segoe UI/Consolas (Windows).

## Most important habit

Re-run the closest-prior-art search protocol (03_Research_Gaps/Closest_Prior_Art_Tracker.md) at every phase gate and within two weeks of submission.
"""
    wr("00_README.md", readme)

    import fitz
    print("Bibliography:", stats)
    for k, p in pdf.items():
        d = fitz.open(p); print(os.path.basename(p), d.page_count, "pages", round(os.path.getsize(p) / 1e6, 2), "MB"); d.close()
    for k, p in wbs.items():
        print(os.path.basename(p), round(os.path.getsize(p) / 1e3, 1), "KB")
    print("Figures:", len(figs))
    print("Unresolved citation IDs:", sorted(warns) if warns else "none")


if __name__ == "__main__":
    main()
