# -*- coding: utf-8 -*-
"""Research idea matrix (15 ideas). Scores are the research team's judgement (0-10), not empirical results.
Overall score (computed in Excel with formulas) = weighted sum using WEIGHTS below."""

IDEAS = [
dict(id="I01", title="Where Does Machine-Learning Alpha Come From After Trading Costs? Nonlinearity, State Dependence and Cost-Aware Learning in Signal Combination",
     rq="How much of the net-of-cost value of ML signal combination is due to (a) nonlinear signal interactions, (b) state-dependent signal weights, (c) a cost-aware economic training objective, and (d) forecast-uncertainty shrinkage, and do these components interact?",
     hypothesis="Nonlinearity mainly raises gross IC; most net value comes from the cost-aware objective; state dependence adds net value only when trading costs are internalised (interaction effect).",
     literature="GKX2020; ACM2023; JKMP2026; DMNU2020; SWZ2023; DMU2024; NRRZ2024; CHK2024; AHV2023; LMNS2025",
     solved="ML beats linear gross (GKX2020); ML alpha fragile to restrictions/costs (ACM2023, BHHH2023); cost-aware ML weight learning improves the implementable frontier (JKMP2026); conditional multifactor weights survive costs at factor level (DMU2024).",
     unsolved="No unified, nested attribution of net value to nonlinearity vs conditioning vs objective vs uncertainty on one signal library, one cost model and one inference framework [inference from literature search; re-check before submission].",
     novelty_text="Factorial (2x2x2x2) nested design + multiple-testing-robust attribution (SPA/MCS, DSR, PBO) + economic mechanism tests (limits to arbitrage, liquidity regimes).",
     data="CRSP, Compustat (WRDS), JKP characteristics or Open Source AP signals, FF/q factors, FRED/Welch-Goyal state variables, spread estimates",
     signals="~150 published characteristics in 13 themes; liquidity/cost features", ml="Ridge; LightGBM; NN ensemble; gated mixture-of-experts; Portfolio-ML-style economic loss",
     portfolio="Common TC-aware mean-variance optimiser with partial adjustment (GP2013-style) and constraints", benchmark="1/N signals, IC-weighted, Lewellen FM, KNS SDF, GKX NN, JKMP Portfolio-ML, DMNU linear PPP",
     experiments="16 factorial cells x 3 AUM levels x robustness grid", metrics="IC/RankIC, OOS R2, gross/net Sharpe, turnover, capacity, net alpha, CE utility",
     difficulties="Compute; honest trial counting; cost calibration; avoiding benchmark underpowering", novelty=8, practical=9, publication=8, data_feas=8, complexity=7, risk=4,
     journals="RFS (stretch); JFQA, Management Science (target); Quantitative Finance, JFM, JBF (backup)"),
dict(id="I02", title="Forecasting Signal Efficacy: A Meta-Model for Dynamic Alpha Allocation under Decay and Crowding",
     rq="Can signal-level features (recent IC, publication age, turnover, valuation spread, crowding proxies, volatility) predict each signal's next-period net contribution, and does stock-level allocation on these forecasts beat static combination net of costs?",
     hypothesis="Signal efficacy is predictable (factor momentum, valuation spreads) but the net benefit is concentrated in low-turnover signals.",
     literature="NRRZ2024; HKS2020; EL2022; KNNV2024; MP2016; CV2023",
     solved="Factor returns are timeable at portfolio level (NRRZ2024, HKS2020); signals decay post-publication (MP2016).",
     unsolved="Timing information implemented at stock level with netting and costs; crowding measures inside the meta-model.",
     novelty_text="Two-level model (signal-efficacy forecasts -> stock-level cost-aware portfolio)", data="Same as I01 + short interest, 13F ownership",
     signals="Same library + signal-level meta-features", ml="Panel GBDT/ridge on signal-month panel; hierarchical shrinkage",
     portfolio="TC-aware optimiser", benchmark="Static combination; NRRZ PLS timing; factor momentum", experiments="Signal-month panel forecasting; allocation backtests",
     metrics="Signal-level R2; portfolio net Sharpe; turnover", difficulties="Few independent time-series observations per signal; overfitting timing",
     novelty=7, practical=9, publication=7, data_feas=8, complexity=6, risk=6, journals="RAPS, JFQA (target); JBF, JEF, IJF (backup)"),
dict(id="I03", title="Uncertainty-Aware Alpha Combination: Forecast Confidence, Robust Optimisation and Turnover",
     rq="Does using stock-level forecast uncertainty (deep ensembles, bootstrap standard errors) to shrink alpha and set robust-optimisation budgets improve net performance and reduce turnover?",
     hypothesis="Uncertainty shrinkage lowers turnover more than it lowers gross alpha, raising net Sharpe.",
     literature="LMNS2025; BS2022; GI2003; LPB2017; KZ2007", solved="Closed-form NN forecast SEs and uncertainty-averse portfolios (LMNS2025, working paper).",
     unsolved="Interaction with trading costs and dynamic trading; comparison of uncertainty estimators in stock-level optimisation.",
     novelty_text="Uncertainty -> cost-aware robust optimiser; calibration of uncertainty to realised errors", data="As I01",
     signals="As I01", ml="Deep ensembles, MC dropout, bootstrap SEs, conformal intervals", portfolio="Robust MVO with ellipsoidal uncertainty + TC",
     benchmark="Point forecasts; James-Stein alpha shrinkage; LMNS2025 method", experiments="Estimator x optimiser grid", metrics="Calibration, net Sharpe, turnover",
     difficulties="Closest prior art is very recent; risk of incremental contribution", novelty=6, practical=8, publication=6, data_feas=8, complexity=6, risk=5,
     journals="Quantitative Finance, JFEc (target); JEF, EJOR (backup)"),
dict(id="I04", title="Differentiable Cost-Aware Portfolio Layers for High-Dimensional Equity Signal Combination",
     rq="Can end-to-end training through a differentiable, constrained, cost-aware QP scale to 1,000+ stocks and beat two-stage predict-then-optimise net of costs?",
     hypothesis="End-to-end training helps most when constraints bind and costs are high.", literature="BK2023; CI2023; ULM2024; EG2022; AAB2019; JKMP2026",
     solved="End-to-end MVO on small universes (BK2023, ULM2024); decision-focused losses (EG2022).", unsolved="Large cross-sections with realistic constraints and costs; stability.",
     novelty_text="Scalable implicit differentiation with factor-structured covariance and TC", data="As I01", signals="As I01", ml="NN signal combiner + differentiable QP",
     portfolio="Differentiable TC-aware QP", benchmark="Two-stage; JKMP2026", experiments="Scalability; net performance", metrics="Net utility, runtime, stability",
     difficulties="Compute, gradient instability, local optima", novelty=7, practical=7, publication=6, data_feas=8, complexity=9, risk=7,
     journals="Management Science, Operations Research, INFORMS JOC (target); QF, EJOR (backup)"),
dict(id="I05", title="Regime-Gated Mixture-of-Experts for Alpha Signal Combination",
     rq="Do gated experts conditioned on market states (volatility, liquidity, sentiment, momentum-crash states) outperform global models net of costs?",
     hypothesis="Gating helps in crash/illiquid states (momentum, short-leg anomalies) but adds turnover.", literature="CPZ2024; DM2016; SYY2012; CDS2020; SYM2025; JJNH1991",
     solved="Anomalies are state-dependent (SYY2012, MPR2026); momentum crashes are predictable (DM2016).", unsolved="Learned gating for many signals with costs.",
     novelty_text="MoE with economically interpretable gates", data="As I01 + state variables", signals="As I01", ml="MoE, jump-model regimes",
     portfolio="TC-aware optimiser", benchmark="Global GBDT/NN with state interactions", experiments="Gate variants; placebo regimes", metrics="Net Sharpe; regime-conditional IC",
     difficulties="Few regime episodes; overfitting", novelty=6, practical=8, publication=6, data_feas=8, complexity=7, risk=7, journals="QF, JBF, JEF (target)"),
dict(id="I06", title="Learning Signal Decay: Horizon-Aware Combination with Aim Portfolios",
     rq="Can ML estimate signal-specific alpha term structures and embed them in Garleanu-Pedersen aim portfolios to reduce costs?",
     hypothesis="Weighting by persistence cuts turnover without sacrificing gross alpha.", literature="GP2013; BHHH2023; JKMP2026",
     solved="Theory (GP2013); horizon matters for ML (BHHH2023); multi-horizon forecasts inside cost-aware portfolios (JKMP2026).",
     unsolved="Explicit learned decay per signal/stock and its interpretability [inference].", novelty_text="Decay-structure estimation", data="As I01",
     signals="As I01", ml="Multi-horizon multi-task models", portfolio="GP aim portfolio", benchmark="JKMP2026 Markowitz-ML", experiments="Horizon grid",
     metrics="Net Sharpe, turnover", difficulties="Overlap with JKMP2026", novelty=5, practical=8, publication=5, data_feas=8, complexity=6, risk=5, journals="QF, JFM"),
dict(id="I07", title="Netting-Aware Signal Selection: Which Signals Earn Their Keep in a Combined Portfolio?",
     rq="What is each signal's marginal net contribution when trades from different signals cancel?", hypothesis="High-turnover signals add value only through netting with slow signals.",
     literature="DMNU2020; NMV2016; CV2023", solved="Netting increases significant characteristics (DMNU2020, linear).", unsolved="Nonlinear marginal contributions; attribution method.",
     novelty_text="Shapley-style net-of-cost marginal contribution", data="As I01", signals="As I01", ml="Linear + GBDT", portfolio="TC-aware optimiser",
     benchmark="Stand-alone signal net returns", experiments="Leave-one-theme-out", metrics="Marginal net utility", difficulties="Combinatorics", novelty=6, practical=9, publication=6,
     data_feas=9, complexity=5, risk=4, journals="JFQA, FAJ, JFM"),
dict(id="I08", title="Crowding-Aware Alpha Combination", rq="Do crowding proxies (short interest, institutional ownership changes, valuation spreads) predict signal crashes and improve combination?",
     hypothesis="Crowded signals should be down-weighted before crashes.", literature="MP2016; EL2022; LS2008", solved="Partial evidence on crowding and factor crashes.",
     unsolved="Stock-level implementation with costs; clean crowding measures.", novelty_text="Crowding meta-features", data="As I01 + 13F, short interest (Compustat)",
     signals="As I01", ml="Meta-model", portfolio="TC-aware", benchmark="Static", experiments="Crash prediction", metrics="Tail risk, net Sharpe",
     difficulties="Crowding measurement noise; data access", novelty=6, practical=8, publication=5, data_feas=6, complexity=6, risk=7, journals="JFM, JBF"),
dict(id="I09", title="Transfer Learning of Alpha Combination Across 90+ Markets", rq="Do combination functions learned in the US transfer to other markets, and does domain adaptation help net of local costs?",
     hypothesis="Nonlinear structure transfers partially; cost structures differ.", literature="JKP2023; TH2021; CFMZ2023", solved="Anomalies replicate globally; ML predictability global.",
     unsolved="Transfer of combination functions with local costs.", novelty_text="Domain adaptation", data="JKP global + Datastream/Compustat Global",
     signals="JKP 153", ml="Pretrain-finetune", portfolio="TC-aware", benchmark="Local models", experiments="Country panels", metrics="Net Sharpe by market",
     difficulties="International cost data", novelty=6, practical=7, publication=6, data_feas=6, complexity=7, risk=6, journals="JFQA, RF, JBF"),
dict(id="I10", title="Do Text and LLM Signals Add Net-of-Cost Value to a Mature Signal Library?", rq="What is the incremental net value of news/LLM signals after controlling for 150 characteristics and costs?",
     hypothesis="Fast text signals add gross IC but little net value except through netting.", literature="LLT2023; OP2022; CV2023", solved="LLM scores predict short-term returns.",
     unsolved="Incremental net value in combination.", novelty_text="Incremental-value test with costs", data="RavenPack/news (costly) or EDGAR text",
     signals="Library + text", ml="LLM embeddings + GBDT", portfolio="TC-aware", benchmark="Library-only", experiments="Incremental tests", metrics="Net Sharpe, spanning",
     difficulties="Data cost; look-ahead in LLM training", novelty=7, practical=8, publication=6, data_feas=4, complexity=7, risk=7, journals="JFQA, MS"),
dict(id="I11", title="Graph Neural Signal Propagation with Trading Costs", rq="Do supply-chain/peer graphs improve combination net of costs?",
     hypothesis="Graph signals are slow-moving and cheap to trade.", literature="CF2008", solved="Customer-supplier momentum exists.", unsolved="GNN combination net of costs.",
     novelty_text="GNN in cost-aware setting", data="Compustat segments / FactSet Revere (costly)", signals="Library + graph", ml="GNN", portfolio="TC-aware",
     benchmark="Non-graph", experiments="Graph ablations", metrics="Net Sharpe", difficulties="Graph data PIT", novelty=6, practical=6, publication=5, data_feas=4, complexity=8, risk=7, journals="QF, EJOR"),
dict(id="I12", title="Bayesian Dynamic Model Averaging of Alpha Signals", rq="Does time-varying Bayesian combination beat static and ML combinations?", hypothesis="Simple adaptive shrinkage matches ML net of costs.",
     literature="RSZ2010; KNS2020", solved="Combination beats selection in time series.", unsolved="Cross-sectional dynamic averaging net of costs.", novelty_text="DMA for signals",
     data="As I01", signals="As I01", ml="DMA / discounted least squares", portfolio="TC-aware", benchmark="ML", experiments="Forgetting factors", metrics="Net Sharpe",
     difficulties="Limited novelty", novelty=4, practical=7, publication=5, data_feas=9, complexity=4, risk=4, journals="IJF, JEF"),
dict(id="I13", title="State-Dependent Capacity of ML Alpha", rq="How does the implementable frontier shift across liquidity regimes and AUM?", hypothesis="Capacity collapses in illiquid regimes; cost-aware conditioning preserves it.",
     literature="CDS2020; KS2004; JKMP2026", solved="Theory of liquidity regimes; static capacity estimates.", unsolved="Regime-dependent capacity for ML portfolios.",
     novelty_text="Capacity as function of state", data="As I01 + TAQ", signals="As I01", ml="As I01", portfolio="TC-aware with AUM grid", benchmark="Static cost model",
     experiments="AUM x regime", metrics="Break-even AUM", difficulties="Impact calibration", novelty=6, practical=9, publication=6, data_feas=7, complexity=6, risk=5, journals="JFM, FAJ"),
dict(id="I14", title="Publication-Aware Training: Eliminating Look-Ahead in Signal Discovery", rq="How much ML alpha comes from using signals before they were discovered?",
     hypothesis="A large share of backtested ML alpha pre-2000 relies on undiscovered signals.", literature="MP2016; CHK2024; AHV2023", solved="Partially studied as a design choice (CHK2024, AHV2023).",
     unsolved="Systematic quantification in a cost-aware combination.", novelty_text="Publication-date gating", data="OpenAP signal publication dates", signals="As I01", ml="As I01",
     portfolio="TC-aware", benchmark="Full library", experiments="Gated vs ungated", metrics="Net alpha gap", difficulties="Overlap with existing design-choice papers",
     novelty=4, practical=7, publication=5, data_feas=9, complexity=4, risk=3, journals="CFR, JFM"),
dict(id="I15", title="Alpha-Risk Model Misalignment in ML Portfolios", rq="Does nonlinear ML alpha create systematic misalignment with factor risk models, and does an alignment correction improve realised risk and net returns?",
     hypothesis="ML alpha loads on unmodelled nonlinear factors, causing risk underestimation.", literature="CSS2012; LS2008; KPS2019", solved="Alignment problem documented for linear alphas.",
     unsolved="Alignment for nonlinear ML alphas; learned alignment factors.", novelty_text="Alignment diagnostics for ML", data="As I01", signals="As I01", ml="GBDT/NN",
     portfolio="MVO with alpha alignment factor", benchmark="Standard risk model", experiments="Ex-ante vs ex-post risk", metrics="Risk bias statistic, net IR",
     difficulties="Commercial risk models unavailable; build own", novelty=6, practical=8, publication=5, data_feas=8, complexity=5, risk=5, journals="QF, JPM, FAJ"),
]


# Academic importance (0-10): contribution to the finance literature if the idea succeeds (team judgement).
ACADEMIC = dict(I01=9, I02=7, I03=6, I04=6, I05=5, I06=5, I07=6, I08=5, I09=6, I10=6, I11=5, I12=4, I13=6, I14=5, I15=5)

# Scoring weights used in documents and as editable inputs in Workbook 3.
WEIGHTS = [("Novelty", 0.20), ("Academic importance", 0.15), ("Practical importance", 0.10),
           ("Publication potential", 0.20), ("Data feasibility", 0.15),
           ("Implementation ease (10 - difficulty)", 0.10), ("Safety (10 - failure risk)", 0.10)]
