# -*- coding: utf-8 -*-
"""Core literature matrix (detailed entries).

Evidence convention used in every text field:
  * Plain statements = verified from the publisher page, the paper's abstract, the authors'
    own repository, or a search-result summary of those sources (see `src`).
  * "[inference]" = our reading or research inference, not a claim made by the authors.
  * "[verify]" = detail we could not confirm from an accessible primary source; check the full text.
DOIs are filled from verified searches or from the Crossref check (08_References/crossref_verification.csv).
"""

def L(pid, authors, year, title, venue, tier, category, relevance, doi="", url="", **f):
    d = dict(id=pid, authors=authors, year=year, title=title, venue=venue, tier=tier,
             category=category, relevance=relevance, doi=doi, url=url, core=True)
    d.update(f)
    return d

NA = "n/a"

CORE = [
L("GKX2020", "Gu, S.; Kelly, B.; Xiu, D.", 2020, "Empirical Asset Pricing via Machine Learning",
  "Review of Financial Studies 33(5):2223-2273", "T1 General Finance", "ML asset pricing", 5,
  url="https://academic.oup.com/rfs/article/33/5/2223/5758276",
  rq="Which machine-learning methods best measure stock-level risk premia, and where do their gains come from?",
  data="CRSP/Compustat US equities, monthly, 1957-2016 (NBER w25398)",
  universe="All US common stocks (roughly 30,000 over the sample) [verify exact filters]",
  freq="Monthly",
  features="94 firm characteristics, 74 industry dummies, 8 aggregate macro predictors and characteristic x macro interactions (920 covariates) [verify counts in full text]",
  ml="OLS, OLS-3, PLS, PCR, elastic net, generalized linear model with group lasso, random forest, gradient-boosted trees, neural networks with 1-5 hidden layers",
  signal="Implicit: one pooled panel model maps all characteristics to next-month excess return",
  portfolio="Decile sorts on predicted returns (equal- and value-weighted long-short); market-timing exercise",
  benchmark="OLS with all covariates; OLS-3 (size, book-to-market, momentum)",
  metrics="Out-of-sample R2, Diebold-Mariano tests, variable importance, decile-spread returns and Sharpe ratios",
  period="Expanding training window with separate validation; out-of-sample test 1987-2016 [verify split]",
  tcost="Not modelled in the headline portfolio results [inference from design; verify appendix]",
  turnover="Not a design objective", risk="None beyond sorting",
  result="Trees and neural networks perform best; gains come from nonlinear predictor interactions; price trends, liquidity and volatility are the dominant predictors.",
  contribution="Set the standard comparative design for ML in cross-sectional return prediction.",
  limitation="Gross-of-cost sort portfolios; predictions evaluated by statistical loss, not the investor objective; static mapping over time except via macro interactions.",
  not_solved="Whether the predictive gains survive trading costs, implementable constraints and realistic capacity.",
  extension="Re-run the same model classes inside one cost-aware optimizer and attribute the net gain to nonlinearity, conditioning and objective [inference].",
  gap="Prediction-to-portfolio gap; cost-agnostic evaluation"),

L("ACM2023", "Avramov, D.; Cheng, S.; Metzker, L.", 2023, "Machine Learning vs. Economic Restrictions: Evidence from Stock Return Predictability",
  "Management Science 69(5):2587-2619", "T1b Finance/OR", "ML strategies & implementability", 5,
  doi="10.1287/mnsc.2022.4449", url="https://pubsonline.informs.org/doi/abs/10.1287/mnsc.2022.4449",
  rq="Do deep-learning return signals survive economic restrictions such as excluding microcaps, distressed firms and high-volatility episodes, and trading costs?",
  data="US equities; ML models from the recent literature (neural networks, conditional autoencoder, IPCA, adversarial SDF) [verify full list]",
  universe="US common stocks, with subsamples excluding microcaps and distressed firms", freq="Monthly",
  features="Firm characteristics as in the replicated ML models", ml="Deep learning / latent-factor ML models",
  signal="Model-implied expected returns / pricing-kernel weights", portfolio="Long-short and tangency portfolios implied by the models",
  benchmark="Unrestricted ML portfolios versus restricted universes", metrics="Returns, alphas, turnover, net returns",
  period="Out-of-sample US sample [verify dates]",
  tcost="Reasonable trading costs applied; performance deteriorates because of high turnover and extreme positions",
  turnover="High; identified as the main source of cost drag", risk="Universe restrictions act as economic filters",
  result="ML profitability comes from difficult-to-arbitrage stocks and high limits-to-arbitrage states; excluding microcaps, distressed stocks or high-volatility episodes considerably attenuates it; costs erode it further.",
  contribution="Showed that headline ML alpha is concentrated where it is least implementable.",
  limitation="Diagnoses the problem; does not propose a combination method that is implementable by design.",
  not_solved="How to build ML signal combinations whose value survives restrictions and costs.",
  extension="Use its restrictions as the default universe and report results both with and without them [inference].",
  gap="Implementability of ML alpha"),

L("JKMP2026", "Jensen, T.I.; Kelly, B.; Malamud, S.; Pedersen, L.H.", 2026, "Machine Learning and the Implementable Efficient Frontier",
  "Review of Financial Studies (published online 2026)", "T1 General Finance", "ML strategies & implementability", 5,
  doi="10.1093/rfs/hhag022", url="https://github.com/theisij/ml-and-the-implementable-efficient-frontier",
  rq="How should ML be used so that portfolios deliver the best risk-return trade-off net of trading costs?",
  data="JKP global characteristics dataset (US monthly characteristics, daily and monthly returns); WRDS access required (code README)",
  universe="US stocks", freq="Monthly characteristics; daily returns for risk estimation",
  features="JKP firm characteristics (about 150, clustered into 13 themes)",
  ml="Ridge-type regressions on random Fourier features; separate models for returns at horizons t+1..t+12 (code README)",
  signal="Learned jointly with the portfolio objective in Portfolio-ML; prediction-first in Markowitz-ML / Static-ML",
  portfolio="Trading-cost-aware optimisation; methods compared: Portfolio-ML, Static-ML, Static-ML*, Markowitz-ML, portfolio sorts",
  benchmark="Markowitz-ML, portfolio sort, 1/N, market [verify full list]",
  metrics="Implementable efficient frontier (net return per unit of risk), net Sharpe ratio, utility, economic feature importance",
  period="US out-of-sample period [verify dates]",
  tcost="Explicit trading-cost model entering the optimisation (price impact increasing in trade size relative to liquidity) [verify calibration]",
  turnover="Controlled endogenously through the cost-aware objective", risk="Covariance estimate inside the mean-variance utility",
  result="After costs, Markowitz-ML and sorts have downward-bending frontiers; Static-ML earns positive net Sharpe but negative utility unless tuned; Portfolio-ML, which learns weights under an economic objective, works best out of sample.",
  contribution="Moved ML evaluation from gross prediction to the implementable frontier; introduced economic feature importance.",
  limitation="[inference] The paper's focus is the cost-aware objective; explicit state- or regime-dependence of signal weights and forecast uncertainty are not its central questions (verify in full text).",
  not_solved="[inference] How much of the net gain comes from nonlinearity versus conditioning versus the objective; whether conditioning on market states adds value once costs are internalised.",
  extension="Use Portfolio-ML as the strongest benchmark and nest it inside a factorial decomposition [inference].",
  gap="Closest prior art for any cost-aware ML combination claim"),

L("DMNU2020", "DeMiguel, V.; Martin-Utrera, A.; Nogales, F.J.; Uppal, R.", 2020, "A Transaction-Cost Perspective on the Multitude of Firm Characteristics",
  "Review of Financial Studies 33(5):2180-2222", "T1 General Finance", "Portfolio construction", 5,
  doi="10.1093/rfs/hhz085", url="https://academic.oup.com/rfs/article-abstract/33/5/2180/5821387",
  rq="How do transaction costs change the number of characteristics that matter jointly for an investor's optimal portfolio?",
  data="US equities with a large set of firm characteristics [verify count and dates]", universe="US common stocks", freq="Monthly",
  features="Firm characteristics", ml="Parametric portfolio policy (linear in characteristics) with regularisation",
  signal="Characteristic weights estimated by maximising investor utility net of costs",
  portfolio="Parametric portfolio policy with transaction costs", benchmark="Policies ignoring costs; subsets of characteristics",
  metrics="Significance of characteristics; out-of-sample utility / Sharpe net of costs", period="[verify]",
  tcost="Explicit, inside the objective", turnover="Endogenous", risk="Utility-based",
  result="Transaction costs increase the number of jointly significant characteristics from 6 to 15, because trades implied by different characteristics partly cancel out (netting).",
  contribution="Showed that combining many signals is valuable precisely because of trade netting under costs.",
  limitation="Linear policy; static weights.",
  not_solved="Nonlinear and state-dependent combinations under costs.",
  extension="Measure netting benefits explicitly for nonlinear and conditional combinations [inference].",
  gap="Linear/static cost-aware combination only"),

L("BSCV2009", "Brandt, M.W.; Santa-Clara, P.; Valkanov, R.", 2009, "Parametric Portfolio Policies: Exploiting Characteristics in the Cross-Section of Equity Returns",
  "Review of Financial Studies 22(9):3411-3447", "T1 General Finance", "Portfolio construction", 4,
  doi="10.1093/rfs/hhp003", url="https://academic.oup.com/rfs/article-abstract/22/9/3411/1572695",
  rq="Can portfolio weights be modelled directly as a function of stock characteristics instead of estimating return distributions?",
  data="US equities [verify dates]", universe="US common stocks", freq="Monthly",
  features="Size, book-to-market, momentum", ml="Parametric (linear) weight function estimated by maximising average utility",
  signal="Weights tilt linearly on standardized characteristics", portfolio="Benchmark weights plus characteristic tilts",
  benchmark="Market portfolio", metrics="Certainty equivalent, Sharpe", period="[verify]",
  tcost="Extension discussed [verify]", turnover="Reported [verify]", risk="Utility (CRRA)",
  result="Direct weight modelling scales to large cross-sections and delivers economically large gains.",
  contribution="Foundation of learning portfolio weights under an economic objective.",
  limitation="Linear, few characteristics, static coefficients.", not_solved="Nonlinearity, many signals, costs, state dependence.",
  extension="Nonlinear/conditional PPP generalisations (see DMNU2020, SWZ2023, JKMP2026).", gap="Static linear policies"),

L("GP2013", "Garleanu, N.; Pedersen, L.H.", 2013, "Dynamic Trading with Predictable Returns and Transaction Costs",
  "Journal of Finance 68(6):2309-2340", "T1 General Finance", "Portfolio construction", 5,
  doi="10.1111/jofi.12080", url="https://onlinelibrary.wiley.com/doi/abs/10.1111/jofi.12080",
  rq="What is the optimal dynamic portfolio when returns are predictable by signals with different decay speeds and trading is costly?",
  data="Commodity futures application [verify]", universe="Futures", freq="Daily [verify]",
  features="Return-predicting signals with different mean-reversion speeds", ml=NA,
  signal="Signals weighted by their persistence: slower signals get more weight in the aim portfolio",
  portfolio="Closed-form: trade partially toward an aim portfolio that is itself a weighted average of current and expected future Markowitz portfolios",
  benchmark="Myopic / static strategies", metrics="Net utility, Sharpe", period="[verify]",
  tcost="Quadratic costs, proportional to risk", turnover="Endogenous (partial adjustment)", risk="Mean-variance",
  result="Two principles: aim in front of the target and trade partially toward it.",
  contribution="Theory of how signal decay and costs jointly determine the combination and trading speed.",
  limitation="Linear signals, known dynamics, quadratic costs.", not_solved="Learning signal decay and nonlinear signal interactions from data.",
  extension="Estimate signal-specific decay with ML and embed in the aim portfolio [inference].", gap="Known-parameter theory"),

L("CDS2020", "Collin-Dufresne, P.; Daniel, K.; Saglam, M.", 2020, "Liquidity Regimes and Optimal Dynamic Asset Allocation",
  "Journal of Financial Economics 136(2):379-406", "T1 General Finance", "Factor timing & regimes", 5,
  url="https://www.sciencedirect.com/science/article/abs/pii/S0304405X19302302",
  rq="How should a costly trader allocate when expected returns, covariances and trading costs follow a regime-switching model?",
  data="Model with calibrated application [verify]", universe="Multi-asset", freq=NA, features="Regime states", ml=NA,
  signal="Regime-weighted conditional mean-variance portfolios", portfolio="Aim portfolio = weighted average of conditional MV portfolios across future states",
  benchmark="Single-regime solution", metrics="Utility", period=NA, tcost="Regime-dependent quadratic costs",
  turnover="Trading speed higher in persistent, riskier and more liquid states", risk="Mean-variance",
  result="Trading speed should vary with the regime; it can be optimal to overweight low-Sharpe assets that stay liquid in crises.",
  contribution="Theoretical case for state-dependent combination and trading speed under costs.",
  limitation="Regimes and parameters assumed known; low-dimensional.", not_solved="Empirical, high-dimensional, learned version for stock-level signals.",
  extension="Test its predictions (state-dependent trading speed) in an ML signal-combination setting [inference].", gap="Theory without large-scale empirical test"),

L("NRRZ2024", "Neuhierl, A.; Randl, O.; Reschenhofer, C.; Zechner, J.", 2024, "Timing the Factor Zoo",
  "Working paper (SSRN 4376898); AFA/AEA conference programmes", "WP", "Factor timing & regimes", 5,
  url="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4376898",
  rq="Can the returns of hundreds of equity factors be timed with a high-dimensional set of predictors?",
  data="300+ equity risk factors and a high-dimensional predictor set", universe="US factor portfolios", freq="Monthly",
  features="Factor-specific and aggregate predictors (past factor returns, volatility, valuation, macro, etc.)",
  ml="Partial least squares and other dimension-reduction/shrinkage methods",
  signal="Timed factor weights", portfolio="Timed multifactor portfolio", benchmark="Untimed multifactor portfolio",
  metrics="Predictive R2, factor portfolio returns", period="[verify]", tcost="[verify treatment]", turnover="[verify]", risk="[verify]",
  result="Almost all factor groups can be timed, most for profitability and value; past factor returns and volatility are the best single predictors but PLS aggregation dominates; timing raises the multifactor portfolio return by about 20%.",
  contribution="Most comprehensive evidence that factor (signal) efficacy is predictable over time.",
  limitation="Operates at the factor-portfolio level; stock-level netting and implementable costs are not the focus [inference].",
  not_solved="Whether factor-timing information survives when combined at the stock level inside a cost-aware optimizer [inference].",
  extension="Feed timing predictors as state variables into stock-level combination [inference].", gap="Factor-level, not stock-level implementation"),

L("DMU2024", "DeMiguel, V.; Martin-Utrera, A.; Uppal, R.", 2024, "A Multifactor Perspective on Volatility-Managed Portfolios",
  "Journal of Finance 79:3859-3891", "T1 General Finance", "Factor timing & regimes", 5,
  doi="10.1111/jofi.13395", url="https://onlinelibrary.wiley.com/doi/full/10.1111/jofi.13395",
  rq="Can conditioning factor weights on volatility add value out of sample and net of costs in a multifactor setting?",
  data="US factor portfolios; replication package on Mendeley Data", universe="Factor portfolios", freq="Monthly",
  features="Factor volatilities", ml=NA, signal="Conditional multifactor weights",
  portfolio="Conditional multifactor portfolio", benchmark="Unconditional multifactor and single-factor volatility-managed portfolios",
  metrics="Out-of-sample Sharpe net of costs", period="[verify]", tcost="Explicit", turnover="Explicit", risk="Mean-variance",
  result="Single-factor volatility management does not survive costs, but a conditional multifactor portfolio outperforms its unconditional counterpart out of sample and net of costs; factor risk prices generally fall with market volatility.",
  contribution="Evidence that state-conditional combination can survive costs when done jointly across factors.",
  limitation="Low-dimensional factor set; one conditioning variable family.", not_solved="Stock-level, high-dimensional, nonlinear conditioning.",
  extension="Generalise conditioning to many states and signals at stock level [inference].", gap="State conditioning in low dimension"),

L("HKS2020", "Haddad, V.; Kozak, S.; Santosh, S.", 2020, "Factor Timing", "Review of Financial Studies 33(5):1980-2018",
  "T1 General Finance", "Factor timing & regimes", 4, doi="10.1093/rfs/hhaa017",
  url="https://academic.oup.com/rfs/article-abstract/33/5/1980/5753962",
  rq="Are the dominant components of anomaly returns predictable, and what does that imply for the SDF?",
  data="US anomaly portfolios", universe="Anomaly long-short portfolios", freq="Monthly",
  features="Book-to-market ratios of principal-component portfolios", ml="PCA + predictive regressions with shrinkage",
  signal="Timed principal-component portfolios", portfolio="Optimal factor-timing portfolio", benchmark="Static factor investing",
  metrics="Predictive R2, Sharpe", period="[verify]", tcost="[verify]", turnover="[verify]", risk="Mean-variance",
  result="Market-neutral factors are strongly and robustly predictable; timing substantially improves performance relative to static factor investing.",
  contribution="Shows the optimal timing portfolio equals the SDF; disciplined low-dimensional timing.",
  limitation="Factor-level; gross of stock-level implementation [inference].", not_solved="Stock-level implementation of timed signals.",
  extension="Use PC-valuation predictors as state variables [inference].", gap="Factor-level timing"),

L("CHK2024", "Chen, M.; Hanauer, M.X.; Kalsbach, T.", 2024, "Design Choices, Machine Learning, and the Cross-Section of Stock Returns",
  "Working paper (SSRN 5031755)", "WP", "ML strategies & implementability", 5,
  url="https://ssrn.com/abstract=5031755",
  rq="How much do researcher design choices change ML-based return-prediction portfolios?",
  data="US equities with anomaly inputs", universe="US stocks, with/without microcaps", freq="Monthly",
  features="Anomaly characteristics; with/without compression; pre-publication-only variants",
  ml="Multiple ML models across 1,056 design combinations",
  signal="Varies by design", portfolio="Top-minus-bottom portfolios", benchmark="Across-design distribution",
  metrics="Mean top-minus-bottom returns; non-standard errors", period="[verify]", tcost="[verify]", turnover="[verify]", risk=NA,
  result="Seven design choices (model, target, target transformation, pre-publication inputs, feature compression, rolling vs expanding window, microcaps) generate monthly top-minus-bottom returns from 0.13% to 1.98%; the non-standard error exceeds the standard error by 59%.",
  contribution="Quantified non-standard errors in ML asset-pricing research.",
  limitation="Documents dispersion; not a combination method.", not_solved="Which choices create net-of-cost value and why.",
  extension="Adopt multiverse reporting for our design [inference].", gap="Methodological robustness standard"),

L("LAL2025", "Lalwani, V.; Meshram, V.; Jindal, V.", 2025, "Empirical Asset Pricing via Machine Learning: The Role of Research Design Choices",
  "European Financial Management", "T2 Quant/Field", "ML strategies & implementability", 4,
  doi="10.1111/eufm.70033", url="https://onlinelibrary.wiley.com/doi/10.1111/eufm.70033",
  rq="How do eight research design choices, including training window, data filters and portfolio construction, affect ML strategy profits?",
  data="Equity panel [verify market and dates]", universe="[verify]", freq="Monthly",
  features="Firm characteristics", ml="Seven ML models", signal="Model forecasts", portfolio="5,376 portfolios across design choices",
  benchmark="Distribution across designs", metrics="Returns, non-standard errors, net returns", period="[verify]",
  tcost="Considered", turnover="[verify]", risk=NA,
  result="Non-standard errors are up to five times the standard errors; about one-third of portfolios earn significant returns after costs.",
  contribution="Extends non-standard-error evidence to portfolio construction choices.", limitation="Not a new combination method.",
  not_solved="Economic source of the dispersion.", extension="Multiverse robustness appendix [inference].", gap="Robustness standard"),

L("BHHH2023", "Blitz, D.; Hanauer, M.X.; Hoogteijling, T.; Howard, C.", 2023, "The Term Structure of Machine Learning Alpha",
  "Journal of Financial Data Science 5(4)", "T3 Practitioner", "ML strategies & implementability", 5,
  url="https://www.pm-research.com/content/iijjfds/5/4/40",
  rq="Does ML alpha survive costs, and does training on longer prediction horizons help?",
  data="US equities [verify]", universe="[verify]", freq="Monthly", features="Firm characteristics",
  ml="Common ML models (trees, neural networks) [verify]", signal="Forecasts at 1-12 month horizons",
  portfolio="Long-short portfolios with efficient trading rules", benchmark="1-month-horizon models",
  metrics="Gross and net alpha", period="Full sample and 2004-2021 subperiod",
  tcost="Explicit", turnover="Much lower for long-horizon models", risk=NA,
  result="Common ML models have high full-sample gross alphas but net performance near zero after 2004; training on longer horizons (3, 6, 12 months) and efficient trading rules yields significantly positive net returns.",
  contribution="Showed horizon choice is a first-order lever for net ML alpha.",
  limitation="Horizon is fixed per model, not adapted to states or signals.", not_solved="Signal-specific and state-specific horizons.",
  extension="Let horizon/decay enter the combination explicitly [inference].", gap="Cost-aware horizon design"),

L("AHV2023", "Azevedo, V.; Hoegner, C.; Velikov, M.", 2023, "The Expected Returns on Machine-Learning Strategies",
  "Working paper (SSRN 4702406); AFA programme", "WP", "ML strategies & implementability", 5,
  url="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4702406",
  rq="What are the expected returns of ML anomaly-combination strategies after costs, post-publication decay and the modern high-liquidity era?",
  data="US anomaly characteristics", universe="US stocks", freq="Monthly", features="Published anomaly characteristics",
  ml="Range from simple to sophisticated ML, including LSTM", signal="ML combination of anomaly characteristics",
  portfolio="Long-short, value-weighted variants", benchmark="Simple combinations; factor models",
  metrics="Net returns, generalized net alpha", period="Includes post-decimalization era",
  tcost="Explicit effective-spread costs", turnover="Above 50% for profitable strategies", risk=NA,
  result="Sophisticated ML strategies earn net out-of-sample returns up to 1.42% per month; an LSTM combination has a six-factor generalized net alpha of 1.20% (t = 3.46).",
  contribution="Most direct evidence that some ML combinations remain profitable after costs and decay.",
  limitation="Cost handling is ex post (evaluation), not inside learning [inference].", not_solved="Cost-aware learning and state dependence.",
  extension="Replicate as a benchmark column in the factorial design [inference].", gap="Ex-post cost evaluation"),

L("CV2023", "Chen, A.Y.; Velikov, M.", 2023, "Zeroing In on the Expected Returns of Anomalies",
  "Journal of Financial and Quantitative Analysis 58(3):968-1004", "T1b Finance/OR", "TC & implementability", 5,
  url="https://www.cambridge.org/core/journals/journal-of-financial-and-quantitative-analysis",
  rq="What is the expected return of anomaly strategies net of spreads, post-publication decay and modern trading technology?",
  data="204 anomalies; effective bid-ask spreads", universe="US stocks", freq="Monthly",
  features=NA, ml=NA, signal="Individual anomalies and combinations", portfolio="Long-short with cost mitigation",
  benchmark="Gross returns", metrics="Net expected returns", period="Includes post-2000s era",
  tcost="Effective bid-ask spreads (high- and low-frequency estimates)", turnover="Cost mitigation applied", risk=NA,
  result="Net of these effects, the average anomaly earns about 4 bps per month; cost mitigation works pre-publication but net returns are tiny afterward.",
  contribution="Calibrates realistic expectations for signal-level alpha.", limitation="Mostly single anomalies.",
  not_solved="Whether combination/netting rescues the value.", extension="Use its spread data and horizon to set the cost baseline [inference].",
  gap="Signal-level alpha is small after costs"),

L("NMV2016", "Novy-Marx, R.; Velikov, M.", 2016, "A Taxonomy of Anomalies and Their Trading Costs",
  "Review of Financial Studies 29(1):104-147", "T1 General Finance", "TC & implementability", 5,
  doi="10.1093/rfs/hhv063", url="https://academic.oup.com/rfs/article-abstract/29/1/104/1844518",
  rq="Which anomalies survive trading costs and which mitigation techniques work?",
  data="US anomalies with effective spread estimates", universe="US stocks", freq="Monthly", features=NA, ml=NA,
  signal="Single anomalies; combinations discussed", portfolio="Long-short with buy/hold spreads",
  benchmark="Unmitigated strategies", metrics="Net spreads, turnover, capacity", period="[verify]",
  tcost="Effective bid-ask spreads", turnover="Taxonomy by turnover (<50% per month tends to survive)", risk=NA,
  result="Buy/hold spreads are the most effective mitigation; most anomalies with under 50% monthly turnover earn significant net spreads, few with higher turnover do; size, value and profitability strategies have the most capacity.",
  contribution="Standard reference for anomaly trading costs and mitigation.", limitation="Rule-based mitigation, not optimisation.",
  not_solved="Optimised cost-aware combination.", extension="Buy/hold spread as a strong simple benchmark [inference].", gap="Heuristic mitigation"),

L("FIM2018", "Frazzini, A.; Israel, R.; Moskowitz, T.J.", 2018, "Trading Costs",
  "Working paper (SSRN 3229719)", "WP", "TC & implementability", 4, url="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3229719",
  rq="What are actual institutional trading costs across trade types, stock characteristics, sizes, time and exchanges?",
  data="$1.7 trillion of live trade execution data from a large institutional manager, 21 developed markets, 19 years",
  universe="Developed equity markets", freq="Trade level", features=NA, ml=NA, signal=NA, portfolio=NA, benchmark="Prior cost estimates",
  metrics="Price impact / implementation shortfall", period="19-year sample", tcost="Measured directly", turnover=NA, risk=NA,
  result="Actual trading costs are an order of magnitude smaller than previous studies suggest.",
  contribution="Best available calibration anchor for institutional price impact.", limitation="Single manager's execution; not public data.",
  not_solved=NA, extension="Use as calibration range; run cost-multiplier sensitivity [inference].", gap="Cost calibration uncertainty"),

L("SWZ2023", "Simon, F.; Weibels, S.; Zimmermann, T.", 2026, "Deep Parametric Portfolio Policies",
  "Management Science (2026; Crossref record) - earlier CFR Working Paper 23-01 / SSRN 4150292", "T1b Finance/OR", "End-to-end / decision-focused", 5,
  doi="10.1287/mnsc.2025.00721", url="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4150292",
  rq="Do neural-network parametric portfolio policies beat linear policies?",
  data="US equities with firm characteristics [verify]", universe="US stocks", freq="Monthly", features="Firm characteristics",
  ml="Feed-forward neural networks mapping characteristics to weight tilts", signal="Learned directly from utility",
  portfolio="Deep parametric portfolio policy with weight/leverage constraints", benchmark="Linear parametric portfolio policy",
  metrics="Certainty-equivalent returns", period="[verify]", tcost="Incorporated; results robust after costs [verify whether costs enter training]",
  turnover="[verify]", risk="Utility functions",
  result="Network-based policies achieve 75-276 bps higher monthly certainty-equivalent returns than a comparable linear policy, robust to costs and short-sale restrictions.",
  contribution="Nonlinear generalisation of PPP under an economic objective.", limitation="Static mapping; state dependence and uncertainty not central [inference].",
  not_solved="Decomposition of gains; state conditioning.", extension="Benchmark column; nonlinear-objective cell [inference].", gap="Close prior art (nonlinear economic-objective learning)"),

L("BS2022", "Barroso, P.; Saxena, K.", 2022, "Lest We Forget: Learn from Out-of-Sample Forecast Errors When Optimizing Portfolios",
  "Review of Financial Studies 35(3):1222-1278", "T1 General Finance", "Portfolio construction", 4,
  url="https://academic.oup.com/rfs/article-abstract/35/3/1222/6219970",
  rq="Are errors in historical forecasts of optimisation inputs predictable, and can learning from them improve portfolios?",
  data="Portfolio datasets; replication data on Harvard Dataverse", universe="[verify]", freq="Monthly", features="Past forecast errors",
  ml="Empirical-Bayes-style learning from forecast errors", signal=NA, portfolio="Mean-variance with calibrated inputs",
  benchmark="Sample and shrinkage estimators, 1/N", metrics="Out-of-sample Sharpe, realised vs expected performance",
  period="[verify]", tcost="[verify]", turnover="[verify]", risk="Mean-variance",
  result="Forecast errors have predictable patterns; learning from them yields portfolios whose performance meets expectations.",
  contribution="Links forecast-error learning to optimiser robustness.", limitation="Low-dimensional asset sets.",
  not_solved="Stock-level ML alpha uncertainty.", extension="Calibrate ML alpha scale by realised forecast errors [inference].", gap="Uncertainty-aware inputs"),

L("LMNS2025", "Liao, Y.; Ma, X.; Neuhierl, A.; Schilling, L.", 2025, "The Uncertainty of Machine Learning Predictions in Asset Pricing",
  "Working paper (arXiv 2503.00549)", "WP", "ML asset pricing", 5, url="https://arxiv.org/abs/2503.00549",
  rq="How uncertain are neural-network expected-return forecasts, and does accounting for it improve portfolios?",
  data="Equity panel [verify]", universe="[verify]", freq="Monthly", features="Firm characteristics",
  ml="Neural networks; closed-form and bootstrap standard errors", signal="Forecast confidence intervals",
  portfolio="Uncertainty-averse investment framework (shrinkage interpretation)", benchmark="Point-forecast portfolios",
  metrics="Out-of-sample performance", period="[verify]", tcost="[verify]", turnover="[verify]", risk="Uncertainty aversion",
  result="NN return forecasts share the asymptotic distribution of classic nonparametric estimators, giving closed-form standard errors; using the intervals improves out-of-sample performance.",
  contribution="Formal inference for ML expected returns and its portfolio use.", limitation="Working paper; cost interaction not central [inference].",
  not_solved="Interaction of uncertainty with trading costs and state dependence.", extension="Use as the uncertainty cell and closest prior art for Concept 3 [inference].", gap="Close prior art (uncertainty)"),

L("CHSWZ2025", "Capponi, A.; Huang, C.; Sidaoui, J.A.; Wang, K.; Zou, J.", 2025, "The Nonstationarity-Complexity Tradeoff in Return Prediction",
  "Working paper (arXiv 2512.23596, revised 2026)", "WP", "ML asset pricing", 4, url="https://arxiv.org/abs/2512.23596",
  rq="How should model complexity and training-window length be chosen jointly in non-stationary markets?",
  data="US equity industry portfolios, three decades", universe="Industry portfolios", freq="[verify]", features="[verify]",
  ml="Adaptive joint selection of complexity and window with guarantees", signal=NA, portfolio="[verify]",
  benchmark="Fixed-window and regime-switching benchmarks", metrics="Out-of-sample R2", period="~30 years",
  tcost=NA, turnover=NA, risk=NA,
  result="Adaptive selection improves out-of-sample R2 on industry portfolios by 14% relative to fixed-window and regime-switching benchmarks, with large gains in recessions.",
  contribution="Formalises the window/complexity trade-off.", limitation="Statistical loss; portfolio-level costs not studied [inference].",
  not_solved="Economic value net of costs.", extension="Treat window choice as a design factor [inference].", gap="Nonstationarity"),

L("WL2025", "Wang, Y.; Lera, S.C.", 2025, "Meta-Learning for Return Prediction in Shifting Market Regimes",
  "Journal of Financial Markets", "T2 Quant/Field", "ML asset pricing", 4,
  url="https://www.sciencedirect.com/science/article/abs/pii/S1386418125000825",
  rq="Can a meta-learned prior-fitted network adapt return prediction to regime shifts?",
  data="Two major equity markets [verify]", universe="[verify]", freq="[verify]", features="Firm characteristics [verify]",
  ml="FinPFN: finance-specific prior-data fitted network (meta-learning)", signal="In-context learning", portfolio="[verify]",
  benchmark="State-of-the-art ML benchmarks", metrics="Predictive and portfolio metrics [verify]", period="[verify]",
  tcost="[verify]", turnover="[verify]", risk=NA,
  result="Superior performance relative to ML benchmarks, especially in turbulent periods.",
  contribution="Brings meta-learning / in-context learning to regime-shifting return prediction.", limitation="Implementability not central [inference].",
  not_solved="Net-of-cost value of adaptation.", extension="Adaptive cell in robustness [inference].", gap="Adaptation without costs"),

L("TH2021", "Tobek, O.; Hronec, M.", 2021, "Does It Pay to Follow Anomalies Research? Machine Learning Approach with International Evidence",
  "Journal of Financial Markets 56:100588", "T2 Quant/Field", "ML strategies & implementability", 4,
  url="https://www.sciencedirect.com/science/article/abs/pii/S1386418120300574",
  rq="Do ML aggregations of published anomalies earn out-of-sample returns globally?",
  data="153 anomalies, global equities", universe="US and international; liquid universe", freq="Monthly", features="153 anomaly signals",
  ml="ML aggregation into a single mispricing signal", signal="ML-combined mispricing score", portfolio="Long-short",
  benchmark="Individual anomalies; regional evidence", metrics="Out-of-sample returns", period="[verify]", tcost="Liquid universe", turnover="[verify]", risk=NA,
  result="ML aggregation of all anomalies is profitable around the globe and survives in a liquid universe; non-US past performance does not help pick US winners.",
  contribution="International out-of-sample evidence for ML anomaly aggregation.", limitation="Cost treatment via universe rather than optimiser.",
  not_solved="Cost-aware and state-aware combination.", extension="International robustness template [inference].", gap="Universe filters as cost proxy"),

L("CFMZ2023", "Cakici, N.; Fieberg, C.; Metko, D.; Zaremba, A.", 2023, "Machine Learning Goes Global: Cross-Sectional Return Predictability in International Stock Markets",
  "Journal of Economic Dynamics and Control 155:104725", "T2 Quant/Field", "ML asset pricing", 3,
  url="https://www.sciencedirect.com/science/article/abs/pii/S0165188923001318",
  rq="How does ML return predictability vary across 46 stock markets?",
  data="46 countries, 148 firm characteristics", universe="International stocks", freq="Monthly", features="148 characteristics",
  ml="Repertoire of ML models and their combination", signal="Model combinations", portfolio="Long-short",
  benchmark="Individual models", metrics="Returns, alphas", period="[verify]", tcost="[verify]", turnover="[verify]", risk=NA,
  result="Predictability comes mainly from momentum, reversal, value and size; combining models is particularly effective; performance depends on firm size, recency of information, market breadth and idiosyncratic risk.",
  contribution="Global cross-country evidence.", limitation="Gross focus [verify].", not_solved="Implementable combination.",
  extension="Out-of-US robustness [inference].", gap="International breadth"),

L("LEW2015", "Lewellen, J.", 2015, "The Cross-section of Expected Stock Returns", "Critical Finance Review 4(1):1-44",
  "T2 Quant/Field", "ML asset pricing", 5, url="https://www.nowpublishers.com/",
  rq="How well do Fama-MacBeth combinations of many characteristics predict returns out of sample?",
  data="US equities [verify]", universe="All stocks, excluding tiny stocks, large stocks", freq="Monthly",
  features="Up to 15 firm characteristics [verify]", ml="Fama-MacBeth cross-sectional regressions with rolling slope averages",
  signal="Linear combination with historically averaged slopes", portfolio="Sorts on fitted expected returns",
  benchmark="Individual characteristics", metrics="Predictive slopes, return spreads", period="[verify]", tcost="Not central", turnover="[verify]", risk=NA,
  result="Fitted expected returns from rolling FM slopes have strong out-of-sample predictive power.",
  contribution="The canonical simple linear combination baseline.", limitation="Linear and static.", not_solved="Costs, nonlinearity.",
  extension="Mandatory baseline in our benchmark set [inference].", gap="Strong simple benchmark"),

L("RSZ2010", "Rapach, D.E.; Strauss, J.K.; Zhou, G.", 2010, "Out-of-Sample Equity Premium Prediction: Combination Forecasts and Links to the Real Economy",
  "Review of Financial Studies 23(2):821-862", "T1 General Finance", "Factor timing & regimes", 4, doi="10.1093/rfs/hhp063",
  url="https://academic.oup.com/rfs/article-abstract/23/2/821/1604687",
  rq="Can combining individual predictive-regression forecasts beat the historical average out of sample?",
  data="US equity premium with Welch-Goyal predictors", universe="Market index", freq="Quarterly [verify]", features="Economic predictors",
  ml="Forecast combination (mean, median, trimmed, discount-MSFE)", signal="Forecast combination weights",
  portfolio="Asset allocation utility gains", benchmark="Historical average", metrics="Out-of-sample R2, utility gains", period="[verify]",
  tcost=NA, turnover=NA, risk="Mean-variance investor",
  result="Combination forecasts deliver consistent out-of-sample gains because model uncertainty and instability impair individual models.",
  contribution="Classic evidence that simple combination dominates under instability.", limitation="Time-series market prediction only.",
  not_solved="Cross-sectional signal combination.", extension="Simple averaging as a benchmark for dynamic weights [inference].", gap="Combination vs selection"),

L("CZ2022", "Chen, A.Y.; Zimmermann, T.", 2022, "Open Source Cross-Sectional Asset Pricing", "Critical Finance Review 11(2):207-264",
  "T2 Quant/Field", "Data & measurement", 5, url="https://www.openassetpricing.com/",
  rq="Can the cross-sectional predictor literature be reproduced with open code and data?",
  data="319 characteristics in the paper; website provides 209 firm-level signals (212 incl. 3 CRSP-based) through Dec 2024",
  universe="US stocks", freq="Monthly (daily portfolio returns also available)", features="Published predictors", ml=NA, signal=NA,
  portfolio="Original-paper long-short portfolios", benchmark="Original t-statistics", metrics="Reproduced t-statistics", period="Varies by signal",
  tcost="Not part of the paper [verify]", turnover=NA, risk=NA,
  result="98% of clearly significant predictors reproduce with t > 1.96; slope of reproduced on original t-stats is 0.88 with R2 of 82%.",
  contribution="Open signal library usable as the backbone of a signal-combination study.", limitation="Some inputs require CRSP/Compustat/IBES licences.",
  not_solved=NA, extension="Primary open signal source [inference].", gap="Data infrastructure"),

L("JKP2023", "Jensen, T.I.; Kelly, B.; Pedersen, L.H.", 2023, "Is There a Replication Crisis in Finance?", "Journal of Finance 78(5):2465-2518",
  "T1 General Finance", "Replication & multiple testing", 5, doi="10.1111/jofi.13249",
  url="https://onlinelibrary.wiley.com/doi/full/10.1111/jofi.13249",
  rq="Do published factors replicate, and how should multiple testing be handled?",
  data="153 factors, 93 countries (jkpfactors.com; CC BY-NC 4.0; updated through Dec 2025)", universe="Global", freq="Monthly",
  features="153 characteristics in 13 themes", ml="Bayesian hierarchical model of factor alphas", signal="Theme clusters",
  portfolio="Factor portfolios; tangency portfolio", benchmark="Frequentist multiple-testing corrections", metrics="Replication rates, posterior alphas",
  period="Long global sample", tcost="Not central", turnover=NA, risk=NA,
  result="Most factors replicate, cluster into 13 themes (most in the tangency portfolio), work out of sample across 93 countries, and evidence is strengthened by the number of factors.",
  contribution="Global, documented signal dataset and a Bayesian view of the factor zoo.", limitation="Gross factor returns.",
  not_solved="Implementable combination.", extension="Theme-level attribution and international robustness [inference].", gap="Data infrastructure"),

L("MP2016", "McLean, R.D.; Pontiff, J.", 2016, "Does Academic Research Destroy Stock Return Predictability?", "Journal of Finance 71(1):5-32",
  "T1 General Finance", "Replication & multiple testing", 4, doi="10.1111/jofi.12365",
  url="https://onlinelibrary.wiley.com/doi/abs/10.1111/jofi.12365",
  rq="What happens to anomaly returns out of sample and after publication?",
  data="97 predictors", universe="US stocks", freq="Monthly", features=NA, ml=NA, signal=NA, portfolio="Long-short", benchmark="In-sample returns",
  metrics="Return decay", period="Varies by predictor", tcost=NA, turnover=NA, risk=NA,
  result="Portfolio returns are 26% lower out of sample and 58% lower post-publication.",
  contribution="Documented signal decay after publication.", limitation="Single-signal level.", not_solved="Decay-aware combination.",
  extension="Publication-date-aware signal availability and decay features [inference].", gap="Signal decay"),

L("KMZ2024", "Kelly, B.; Malamud, S.; Zhou, K.", 2024, "The Virtue of Complexity in Return Prediction", "Journal of Finance 79(1):459-503",
  "T1 General Finance", "ML asset pricing", 3, doi="10.1111/jofi.13298",
  url="https://onlinelibrary.wiley.com/doi/full/10.1111/jofi.13298",
  rq="Can models with more parameters than observations improve out-of-sample return prediction?",
  data="US market return with standard predictors", universe="Market index (timing)", freq="Monthly", features="Welch-Goyal-type predictors [verify count]",
  ml="Random Fourier features ridge regression", signal=NA, portfolio="Market-timing strategy", benchmark="Simple models",
  metrics="R2, Sharpe, IR, alpha", period="[verify]", tcost="[verify]", turnover=NA, risk=NA,
  result="Complex models dominate simple ones in theory and US market timing; strategies divest before recessions (14 of 15 out of sample).",
  contribution="Theoretical rationale for high-complexity ML in return prediction.", limitation="Time-series market timing.",
  not_solved="Complexity vs costs in cross-sectional combination.", extension="Complexity dimension in design [inference].", gap="Complexity-cost trade-off"),

L("CPZ2024", "Chen, L.; Pelger, M.; Zhu, J.", 2024, "Deep Learning in Asset Pricing", "Management Science 70(2):714-750",
  "T1b Finance/OR", "ML asset pricing", 4, doi="10.1287/mnsc.2023.4695", url="https://pubsonline.informs.org/doi/10.1287/mnsc.2023.4695",
  rq="Can deep networks estimate a flexible, time-varying SDF for individual stocks using no-arbitrage as the criterion?",
  data="US stocks with firm characteristics and many macroeconomic time series", universe="US stocks", freq="Monthly",
  features="Firm characteristics; macro states extracted from many macro series [verify counts]",
  ml="Adversarial (GAN-style) networks; recurrent networks for macro states", signal="SDF weights conditional on states",
  portfolio="SDF portfolio", benchmark="Linear and other ML SDF models", metrics="SDF Sharpe, explained variation, pricing errors",
  period="[verify]", tcost="Not central", turnover="[verify]", risk=NA,
  result="No-arbitrage criterion, adversarial test assets and macro states improve SDF estimation.",
  contribution="State-dependent deep SDF.", limitation="Implementability; ACM2023 show such portfolios suffer under restrictions.",
  not_solved="Net-of-cost value of state conditioning.", extension="Macro-state extraction ideas for state variables [inference].", gap="State conditioning without costs"),

L("BLDP2014", "Bailey, D.H.; Lopez de Prado, M.", 2014, "The Deflated Sharpe Ratio: Correcting for Selection Bias, Backtest Overfitting, and Non-Normality",
  "Journal of Portfolio Management 40(5):94-107", "T3 Practitioner", "Statistical inference", 5, doi="10.3905/jpm.2014.40.5.094",
  url="https://jpm.pm-research.com/content/40/5/94.abstract",
  rq="How to correct Sharpe ratios for multiple testing and non-normality?", data=NA, universe=NA, freq=NA, features=NA, ml=NA, signal=NA, portfolio=NA,
  benchmark=NA, metrics="Deflated Sharpe ratio", period=NA, tcost=NA, turnover=NA, risk=NA,
  result="DSR corrects for selection bias under multiple testing and non-normal returns.",
  contribution="Standard correction for trial-count inflation.", limitation="Requires honest trial counts and correlation among trials.",
  not_solved=NA, extension="Log every configuration to compute DSR [inference].", gap="Backtest integrity"),

L("MPR2026", "Muller, S.; Preissler, F.", 2026, "In Good and in Bad Times? The Relation between Anomaly Returns and Market States",
  "Journal of Banking & Finance", "T2 Quant/Field", "Factor timing & regimes", 4,
  url="https://www.sciencedirect.com/science/article/pii/S0378426626001202",
  rq="Do anomalies perform differently in good versus bad market states?",
  data="57 countries, 1980-2019 (SSRN version)", universe="International stocks", freq="Monthly / daily [verify]", features="Anomaly portfolios",
  ml=NA, signal=NA, portfolio="Anomaly long-short", benchmark="Good vs bad states", metrics="Four-factor alphas", period="1980-2019 [SSRN version]",
  tcost="[verify]", turnover=NA, risk=NA,
  result="Anomalies perform better in unfavourable market states, driven mostly by the short side (reported magnitudes differ between SSRN and journal versions; verify).",
  contribution="Global evidence of state-dependent anomaly efficacy.", limitation="Descriptive; no combination method.",
  not_solved="Exploiting state dependence implementably.", extension="Motivates state-conditional signal weights [inference].", gap="State dependence of signals"),

L("BLACKROCK2025", "BlackRock Systematic", 2025, "Augmented Investment Management: A systematic framework for designing alpha models",
  "Industry white paper (BlackRock, Nov 2025; for professional investors)", "Industry", "Industry", 3,
  url="https://www.blackrock.com/gls-download/literature/whitepaper/augmented-investment-management.pdf",
  rq="How can ML automate the combination of a large signal library into alpha forecasts for a portfolio optimizer?",
  data="Proprietary signal library (~1,200 stock-selection signals by 2025 per Figure 1); 10-20 years of training data",
  universe="Illustrations on developed-market / MSCI universes", freq="Not specified",
  features="Signals from financial statements, market indicators, news, analyst reports, alternative data",
  ml="Regularised linear models, gradient boosting ensembles, neural networks, proprietary variants; large configuration search; cross-validation",
  signal="Reframes signal weighting as forecasting excess returns (alpha forecasts)",
  portfolio="Separate high-fidelity optimizer with transaction costs, borrow costs, fund constraints; parameters tuned to maximise a metric such as IR",
  benchmark="Discretionary weighting (conceptually); baseline vs defensive model", metrics="Information ratio; illustrative backtests",
  period="Illustrative backtests 2008-2022", tcost="Inside the performance simulator and optimizer; details not disclosed",
  turnover="Not reported", risk="Risk model in optimizer; neutralisation of risk factors optional",
  result="Qualitative framework; illustrative defensive model trained on resampled negative regimes had lower drawdowns but about a 20% performance haircut; Shapley-based attribution reveals a nonlinear volatility effect.",
  contribution="Documents an industrial predict-then-optimize ML pipeline with regime resampling and SHAP-style attribution.",
  limitation="No out-of-sample statistical evidence, no cost-adjusted results, proprietary data; regime-awareness by resampling, not state-conditional weights; hyperparameter search inflates trial counts.",
  not_solved="Whether ML combination adds value net of costs, which component creates it, and how to adapt to signal decay (listed by the authors as ongoing research: adaptive/online learning, domain adaptation).",
  extension="Our design makes each AIM component a testable factor [inference].", gap="Industry framework without inference"),
]
