# -*- coding: utf-8 -*-
"""Broader literature universe (shorter entries). Same evidence conventions as lit_core.py.
Fields: id, authors, year, title, venue, tier, category, relevance, result (what it shows),
limitation/role (how we use it or what it leaves open)."""

def S(pid, authors, year, title, venue, tier, category, relevance, result, role, doi="", url=""):
    return dict(id=pid, authors=authors, year=year, title=title, venue=venue, tier=tier, category=category,
                relevance=relevance, result=result, limitation=role, doi=doi, url=url, core=False)

OTHER = [
# ---------------- ML asset pricing & factor models ----------------
S("GKX2021", "Gu, S.; Kelly, B.; Xiu, D.", 2021, "Autoencoder Asset Pricing Models", "Journal of Econometrics 222(1):429-450", "T2 Quant/Field", "ML asset pricing", 3,
  "Conditional autoencoder links characteristics to nonlinear conditional betas and latent factors under no-arbitrage.", "Latent-factor benchmark; tested under restrictions by ACM2023."),
S("KPS2019", "Kelly, B.; Pruitt, S.; Su, Y.", 2019, "Characteristics Are Covariances: A Unified Model of Risk and Return", "Journal of Financial Economics 134(3):501-524", "T1 General Finance", "ML asset pricing", 3,
  "IPCA: characteristics instrument time-varying loadings; separates risk compensation from an anomaly intercept.", "Risk-based benchmark and risk-model candidate.", doi="10.1016/j.jfineco.2019.05.001"),
S("FNW2020", "Freyberger, J.; Neuhierl, A.; Weber, M.", 2020, "Dissecting Characteristics Nonparametrically", "Review of Financial Studies 33(5):2326-2377", "T1 General Finance", "ML asset pricing", 4,
  "Adaptive group LASSO selects characteristics with incremental information and estimates nonlinear effects; many predictors add nothing incremental; nonlinearity matters.", "Evidence on redundancy; nonparametric-selection benchmark.", doi="10.1093/rfs/hhz123"),
S("KNS2020", "Kozak, S.; Nagel, S.; Santosh, S.", 2020, "Shrinking the Cross-Section", "Journal of Financial Economics 135(2):271-292", "T1 General Finance", "ML asset pricing", 4,
  "Robust SDF from many predictors via an economically motivated prior that shrinks low-variance principal components.", "Mean-variance signal-combination benchmark with shrinkage."),
S("KNS2018", "Kozak, S.; Nagel, S.; Santosh, S.", 2018, "Interpreting Factor Models", "Journal of Finance 73(3):1183-1223", "T1 General Finance", "ML asset pricing", 2,
  "Absence of near-arbitrage implies SDF well summarised by a few high-variance PCs; factor models do not discriminate between behavioural and rational stories.", "Interpretation discipline."),
S("LWZ2022", "Leippold, M.; Wang, Q.; Zhou, W.", 2022, "Machine Learning in the Chinese Stock Market", "Journal of Financial Economics 145(2):64-82", "T1 General Finance", "ML asset pricing", 3,
  "Liquidity is the most important predictor in China; retail presence drives short-term predictability; ML performance economically significant after costs.", "Market-structure dependence of ML signals.", doi="10.1016/j.jfineco.2021.08.017"),
S("DKKM2023", "Didisheim, A.; Ke, S.; Kelly, B.; Malamud, S.", 2023, "Complexity in Factor Pricing Models", "Working paper (NBER w31689; SSRN 4574634)", "WP", "ML asset pricing", 3,
  "Out-of-sample SDF Sharpe and pricing errors improve with model parameterisation; very large factor models outperform simpler ones.", "Complexity dimension; must be confronted with costs."),
S("BPZ2025", "Bryzgalova, S.; Pelger, M.; Zhu, J.", 2025, "Forest through the Trees: Building Cross-Sections of Stock Returns", "Journal of Finance 80:2447-2506", "T1 General Finance", "ML asset pricing", 3,
  "Decision trees (AP-Trees) build characteristic-managed test portfolios that span the SDF.", "Interpretable nonlinear interaction structure.", doi="10.1111/jofi.13477"),
S("CFHH2025", "Cong, L.W.; Feng, G.; He, J.; He, X.", 2025, "Growing the Efficient Frontier on Panel Trees", "Journal of Financial Economics 167:104024", "T1 General Finance", "ML asset pricing", 3,
  "P-Trees on unbalanced panels create test assets and traded factors that advance the efficient frontier.", "Tree-based interaction discovery benchmark."),
S("KMP2023", "Kelly, B.; Malamud, S.; Pedersen, L.H.", 2023, "Principal Portfolios", "Journal of Finance 78(1):347-387", "T1 General Finance", "ML asset pricing", 3,
  "When all signals predict all returns, optimal strategies are eigenvectors of the prediction matrix; principal portfolios earn out-of-sample alphas.", "Cross-asset signal interactions.", doi="10.1111/jofi.13199"),
S("JKX2023", "Jiang, J.; Kelly, B.; Xiu, D.", 2023, "(Re-)Imag(in)ing Price Trends", "Journal of Finance 78(6):3193-3249", "T1 General Finance", "ML asset pricing", 2,
  "CNNs on stock price-chart images extract predictive price patterns.", "Example of new-signal generation, not combination.", doi="10.1111/jofi.13268"),
S("KKMX2025", "Kelly, B.; Kuznetsov, B.; Malamud, S.; Xu, T.A.", 2025, "Artificial Intelligence Asset Pricing Models", "Working paper (NBER w33351)", "WP", "ML asset pricing", 3,
  "Transformer embedded in the SDF shares information across assets; large pricing-error reductions versus prior ML models.", "Attention-based cross-asset combination; implementability untested [inference]."),
S("KX2023", "Kelly, B.; Xiu, D.", 2023, "Financial Machine Learning", "Foundations and Trends in Finance 13(3-4):205-363", "Survey", "ML asset pricing", 4,
  "Survey of ML in financial markets for economists and machine learners.", "Background survey."),
S("GKX2022", "Giglio, S.; Kelly, B.; Xiu, D.", 2022, "Factor Models, Machine Learning, and Asset Pricing", "Annual Review of Financial Economics 14:337-368", "Survey", "ML asset pricing", 3,
  "Survey of factor models and ML methods in asset pricing.", "Background survey. [verify pages]"),
S("LP2020", "Lettau, M.; Pelger, M.", 2020, "Factors That Fit the Time Series and Cross-Section of Stock Returns", "Review of Financial Studies 33(5):2274-2325", "T1 General Finance", "ML asset pricing", 2,
  "RP-PCA estimates factors that price the cross-section by penalising pricing errors.", "Dimension-reduction benchmark for signals."),
S("FGX2020", "Feng, G.; Giglio, S.; Xiu, D.", 2020, "Taming the Factor Zoo: A Test of New Factors", "Journal of Finance 75(3):1327-1370", "T1 General Finance", "Replication & multiple testing", 3,
  "Double-selection LASSO evaluates a new factor's marginal contribution given a high-dimensional set of existing factors.", "Incremental-value testing for new signals."),
S("GLX2021", "Giglio, S.; Liao, Y.; Xiu, D.", 2021, "Thousands of Alpha Tests", "Review of Financial Studies 34(7):3456-3496", "T1 General Finance", "Replication & multiple testing", 3,
  "FDR control for thousands of alpha tests with omitted factors.", "Multiple-testing correction for signal-level claims."),
S("CCY2019", "Chinco, A.; Clark-Joseph, A.D.; Ye, M.", 2019, "Sparse Signals in the Cross-Section of Returns", "Journal of Finance 74(1):449-492", "T1 General Finance", "ML asset pricing", 2,
  "LASSO at high frequency finds sparse, short-lived, unexpected predictors across stocks.", "Fast-decaying signals are costly to trade [inference]."),
S("LMR2017", "Light, N.; Maslov, D.; Rytchkov, O.", 2017, "Aggregation of Information About the Cross Section of Stock Returns: A Latent Variable Approach", "Review of Financial Studies 30(4):1339-1381", "T1 General Finance", "ML asset pricing", 3,
  "Latent-variable (PLS-type) aggregation of many characteristics into expected-return estimates.", "Linear aggregation benchmark."),
S("GHZ2017", "Green, J.; Hand, J.R.M.; Zhang, X.F.", 2017, "The Characteristics that Provide Independent Information about Average U.S. Monthly Stock Returns", "Review of Financial Studies 30(12):4389-4436", "T1 General Finance", "Replication & multiple testing", 3,
  "Few characteristics provide independent information in multivariate FM regressions, and fewer after 2003.", "Redundancy and post-2003 decay evidence."),
S("VBHL2023", "van Binsbergen, J.H.; Han, X.; Lopez-Lira, A.", 2023, "Man versus Machine Learning: The Term Structure of Earnings Expectations and Conditional Biases", "Review of Financial Studies 36(6):2361-2396", "T1 General Finance", "ML asset pricing", 2,
  "Random-forest earnings forecasts reveal conditional analyst biases that predict returns.", "ML-generated signal example."),
S("BBT2021", "Bianchi, D.; Buchner, M.; Tamoni, A.", 2021, "Bond Risk Premiums with Machine Learning", "Review of Financial Studies 34(2):1046-1089", "T1 General Finance", "ML asset pricing", 2,
  "ML (especially neural nets) predicts bond excess returns out of sample.", "Cross-asset generality."),
S("BBCGT2023", "Bali, T.G.; Beckmeyer, H.; Moerke, M.; Weigert, F.", 2023, "Option Return Predictability with Machine Learning and Big Data", "Review of Financial Studies 36(9):3548-3602", "T1 General Finance", "ML asset pricing", 2,
  "ML predicts delta-hedged option returns using many stock and option characteristics.", "Cross-asset generality; option-based signals."),
S("KMN2023", "Kaniel, R.; Lin, Z.; Pelger, M.; Van Nieuwerburgh, S.", 2023, "Machine-Learning the Skill of Mutual Fund Managers", "Journal of Financial Economics 150(1):94-138", "T1 General Finance", "ML asset pricing", 1,
  "Neural nets identify fund outperformance; fund momentum and flows matter, interacting with sentiment.", "ML interpretability example."),
S("LLT2023", "Lopez-Lira, A.; Tang, Y.", 2023, "Can ChatGPT Forecast Stock Price Movements? Return Predictability and Large Language Models", "Working paper (arXiv 2304.07619; SSRN 4412788); reported forthcoming in JFE [verify]", "WP", "ML asset pricing", 2,
  "LLM news scores predict next-day returns and drift, especially small stocks and negative news; returns decline as LLM adoption rises.", "Text-signal candidate; fast decay implies high costs [inference]."),
S("OP2022", "Obaid, K.; Pukthuanthong, K.", 2022, "A Picture Is Worth a Thousand Words: Measuring Investor Sentiment by Combining Machine Learning and Photos from News", "Journal of Financial Economics 144(1):273-297", "T1 General Finance", "ML asset pricing", 1,
  "Photo-based sentiment index predicts market returns and reversals.", "Alternative-data state variable candidate."),
S("KMP2021", "Kelly, B.; Moskowitz, T.J.; Pruitt, S.", 2021, "Understanding Momentum and Reversal", "Journal of Financial Economics 140(3):726-743", "T1 General Finance", "ML asset pricing", 2,
  "Conditional (IPCA) risk explains momentum and reversal via time-varying exposures.", "Interpretation of momentum-type signals."),
S("DA2023", "Zhao, L.; Kong, S.; Shen, Y.", 2023, "DoubleAdapt: A Meta-learning Approach to Incremental Learning for Stock Trend Forecasting", "Proceedings of ACM SIGKDD 2023", "ML venue", "ML asset pricing", 2,
  "Meta-learning data and model adapters for incremental learning under distribution shift in stock forecasting.", "ML-venue adaptive baseline; costs not central [inference]. [verify author list]"),
S("CW2026", "Chen, A.Y.; Welch, I.", 2026, "What Useful Alphas?", "Working paper (arXiv 2607.06502)", "WP", "TC & implementability", 4,
  "About 200 published anomalies: median return 48 bp/month through 2005 falls to 19 bp post-2005 and to about 7 bp after liquidity/microcap restrictions; modest cost allowances eliminate it.", "Sets a sobering prior: net signal-level alpha is near zero recently."),
S("RJ2019", "Rasekhschaffe, K.C.; Jones, R.C.", 2019, "Machine Learning for Stock Selection", "Financial Analysts Journal 75(3):70-88", "T3 Practitioner", "ML strategies & implementability", 4,
  "Practitioner framework: forecast combination across algorithms and feature engineering to limit overfitting in cross-sectional stock selection.", "Practitioner combination baseline.", doi="10.1080/0015198X.2019.1596678"),
S("LLMSS2021", "Leung, E.; Lohre, H.; Mischlich, D.; Shea, Y.; Stroh, M.", 2021, "The Promises and Pitfalls of Machine Learning for Predicting Stock Returns", "Journal of Financial Data Science 3(2):21-50", "T3 Practitioner", "ML strategies & implementability", 3,
  "Compares GBM with OLS on large/mid-cap regional universes; quantifies where ML adds value and its pitfalls.", "Large-cap evidence on ML value."),
S("HK2023", "Hanauer, M.X.; Kalsbach, T.", 2023, "Machine Learning and the Cross-Section of Emerging Market Stock Returns", "Emerging Markets Review 55:101022", "T2 Quant/Field", "ML asset pricing", 2,
  "ML return prediction in emerging markets. [verify volume and details]", "International robustness."),
# ---------------- Replication, multiple testing, meta-science ----------------
S("HLZ2016", "Harvey, C.R.; Liu, Y.; Zhu, H.", 2016, "... and the Cross-Section of Expected Returns", "Review of Financial Studies 29(1):5-68", "T1 General Finance", "Replication & multiple testing", 5,
  "Multiple-testing framework for 300+ factors; new factors should clear t > 3.0.", "Significance hurdles.", doi="10.1093/rfs/hhv059"),
S("HXZ2020", "Hou, K.; Xue, C.; Zhang, L.", 2020, "Replicating Anomalies", "Review of Financial Studies 33(5):2019-2133", "T1 General Finance", "Replication & multiple testing", 4,
  "65% of 452 anomalies fail |t| > 1.96 and 82% fail 2.78 with NYSE breakpoints and value weighting; replicated magnitudes are smaller.", "Microcap and weighting discipline.", doi="10.1093/rfs/hhy131"),
S("HAR2017", "Harvey, C.R.", 2017, "Presidential Address: The Scientific Outlook in Financial Economics", "Journal of Finance 72(4):1399-1440", "T1 General Finance", "Replication & multiple testing", 4,
  "Incentives produce p-hacking; recommends Bayesian-style minimum Bayes factors and higher standards.", "Reviewer expectations on integrity."),
S("COC2011", "Cochrane, J.H.", 2011, "Presidential Address: Discount Rates", "Journal of Finance 66(4):1047-1108", "T1 General Finance", "Replication & multiple testing", 3,
  "Frames the 'zoo' of characteristics and the need to understand which are independently important.", "Motivating question for signal combination."),
S("MENK2024", "Menkveld, A.J.; et al.", 2024, "Nonstandard Errors", "Journal of Finance 79(3):2339-2390", "T1 General Finance", "Replication & multiple testing", 4,
  "164 teams testing the same hypotheses on the same data produce dispersion (non-standard errors) comparable to standard errors.", "Justifies multiverse reporting."),
S("CHEN2021", "Chen, A.Y.", 2021, "The Limits of p-Hacking: Some Thought Experiments", "Journal of Finance 76(5):2447-2480", "T1 General Finance", "Replication & multiple testing", 2,
  "p-hacking cannot plausibly explain the volume of significant anomaly t-statistics.", "Balances HLZ2016 pessimism."),
S("CST2014", "Chordia, T.; Subrahmanyam, A.; Tong, Q.", 2014, "Have Capital Market Anomalies Attenuated in the Recent Era of High Liquidity and Trading Activity?", "Journal of Accounting and Economics 58(1):41-58", "T2 Quant/Field", "TC & implementability", 3,
  "Anomaly returns attenuated in the post-decimalization high-liquidity era.", "Subperiod split rationale."),
# ---------------- Factors, anomalies, regimes ----------------
S("FF1993", "Fama, E.F.; French, K.R.", 1993, "Common Risk Factors in the Returns on Stocks and Bonds", "Journal of Financial Economics 33(1):3-56", "T1 General Finance", "Data & measurement", 3,
  "Three-factor model.", "Alpha benchmark."),
S("FF2015", "Fama, E.F.; French, K.R.", 2015, "A Five-Factor Asset Pricing Model", "Journal of Financial Economics 116(1):1-22", "T1 General Finance", "Data & measurement", 3,
  "Five-factor model adds profitability and investment.", "Alpha benchmark."),
S("CAR1997", "Carhart, M.M.", 1997, "On Persistence in Mutual Fund Performance", "Journal of Finance 52(1):57-82", "T1 General Finance", "Data & measurement", 2,
  "Adds momentum factor to three-factor model.", "Alpha benchmark (UMD)."),
S("HXZ2015", "Hou, K.; Xue, C.; Zhang, L.", 2015, "Digesting Anomalies: An Investment Approach", "Review of Financial Studies 28(3):650-705", "T1 General Finance", "Data & measurement", 3,
  "q-factor model.", "Alpha benchmark."),
S("SY2017", "Stambaugh, R.F.; Yuan, Y.", 2017, "Mispricing Factors", "Review of Financial Studies 30(4):1270-1315", "T1 General Finance", "Data & measurement", 2,
  "Two mispricing factors built from 11 anomalies.", "Alpha benchmark."),
S("AMP2013", "Asness, C.S.; Moskowitz, T.J.; Pedersen, L.H.", 2013, "Value and Momentum Everywhere", "Journal of Finance 68(3):929-985", "T1 General Finance", "Data & measurement", 2,
  "Value and momentum premia across asset classes, negatively correlated with each other.", "Motivates value-momentum combination."),
S("FP2014", "Frazzini, A.; Pedersen, L.H.", 2014, "Betting Against Beta", "Journal of Financial Economics 111(1):1-25", "T1 General Finance", "Data & measurement", 2,
  "Leverage-constrained investors bid up high-beta assets; BAB factor.", "Signal library member."),
S("AHXZ2006", "Ang, A.; Hodrick, R.J.; Xing, Y.; Zhang, X.", 2006, "The Cross-Section of Volatility and Expected Returns", "Journal of Finance 61(1):259-299", "T1 General Finance", "Data & measurement", 2,
  "High idiosyncratic volatility stocks earn low returns.", "Signal library member; cited by BlackRock AIM."),
S("CF2008", "Cohen, L.; Frazzini, A.", 2008, "Economic Links and Predictable Returns", "Journal of Finance 63(4):1977-2011", "T1 General Finance", "Data & measurement", 2,
  "Customer returns predict supplier returns (limited attention).", "Graph/supply-chain signal candidate."),
S("PS2003", "Pastor, L.; Stambaugh, R.F.", 2003, "Liquidity Risk and Expected Stock Returns", "Journal of Political Economy 111(3):642-685", "T1 General Finance", "Data & measurement", 3,
  "Aggregate liquidity measure and liquidity risk premium.", "State variable (market liquidity)."),
S("BW2006", "Baker, M.; Wurgler, J.", 2006, "Investor Sentiment and the Cross-Section of Stock Returns", "Journal of Finance 61(4):1645-1680", "T1 General Finance", "Data & measurement", 3,
  "Sentiment index; hard-to-value stocks mispriced conditional on sentiment.", "State variable (sentiment)."),
S("HJTZ2015", "Huang, D.; Jiang, F.; Tu, J.; Zhou, G.", 2015, "Investor Sentiment Aligned: A Powerful Predictor of Stock Returns", "Review of Financial Studies 28(3):791-837", "T1 General Finance", "Factor timing & regimes", 2,
  "PLS-aligned sentiment index improves market-return prediction.", "State variable alternative."),
S("SYY2012", "Stambaugh, R.F.; Yu, J.; Yuan, Y.", 2012, "The Short of It: Investor Sentiment and Anomalies", "Journal of Financial Economics 104(2):288-302", "T1 General Finance", "Factor timing & regimes", 4,
  "Anomalies are stronger following high sentiment, mostly on the short leg.", "Economic prior for state dependence."),
S("DM2016", "Daniel, K.; Moskowitz, T.J.", 2016, "Momentum Crashes", "Journal of Financial Economics 122(2):221-247", "T1 General Finance", "Factor timing & regimes", 4,
  "Momentum crashes in panic states after market declines when volatility is high; dynamic momentum doubles Sharpe.", "Economic prior: state-dependent momentum weight."),
S("BSC2015", "Barroso, P.; Santa-Clara, P.", 2015, "Momentum Has Its Moments", "Journal of Financial Economics 116(1):111-120", "T1 General Finance", "Factor timing & regimes", 3,
  "Scaling momentum by its own realised variance nearly eliminates crashes.", "Volatility-scaling benchmark."),
S("MM2017", "Moreira, A.; Muir, T.", 2017, "Volatility-Managed Portfolios", "Journal of Finance 72(4):1611-1644", "T1 General Finance", "Factor timing & regimes", 3,
  "Scaling factors by inverse variance increases Sharpe ratios and alphas.", "Conditioning benchmark."),
S("COWY2020", "Cederburg, S.; O'Doherty, M.S.; Wang, F.; Yan, X.S.", 2020, "On the Performance of Volatility-Managed Portfolios", "Journal of Financial Economics 138(1):95-117", "T1 General Finance", "Factor timing & regimes", 3,
  "Volatility-managed strategies generally fail to beat unmanaged versions in real-time out-of-sample tests.", "Caution against in-sample conditioning gains."),
S("KNNV2024", "Kagkadis, A.; Nolte, I.; Nolte, S.; Vasilas, N.", 2024, "Factor Timing with Portfolio Characteristics", "Review of Asset Pricing Studies 14(1):84-118", "T1b Finance/OR", "Factor timing & regimes", 3,
  "Timing factor returns with their portfolios' characteristics outperforms existing timing methods.", "Timing-predictor candidate."),
S("EL2022", "Ehsani, S.; Linnainmaa, J.T.", 2022, "Factor Momentum and the Momentum Factor", "Journal of Finance 77(3):1877-1919", "T1 General Finance", "Factor timing & regimes", 3,
  "Factors are autocorrelated (6 bp after losing years vs 51 bp after winning years); momentum times other factors.", "Signal-level efficacy predictor.", doi="10.1111/jofi.13131"),
S("DLRZ2022", "Dong, X.; Li, Y.; Rapach, D.E.; Zhou, G.", 2022, "Anomalies and the Expected Market Return", "Journal of Finance 77(1):639-681", "T1 General Finance", "Factor timing & regimes", 2,
  "100 anomaly portfolio returns jointly predict the market return out of sample via shrinkage.", "Link between anomalies and aggregate state.", doi="10.1111/jofi.13099"),
S("LT2020", "Lochstoer, L.A.; Tetlock, P.C.", 2020, "What Drives Anomaly Returns?", "Journal of Finance 75(3):1417-1455", "T1 General Finance", "Factor timing & regimes", 2,
  "Decomposes anomaly returns into cash-flow and discount-rate news.", "Economic interpretation."),
S("AB2002", "Ang, A.; Bekaert, G.", 2002, "International Asset Allocation with Regime Shifts", "Review of Financial Studies 15(4):1137-1187", "T1 General Finance", "Factor timing & regimes", 2,
  "Regime-switching correlations and volatilities matter for international allocation.", "Regime-model foundation."),
S("AT2012", "Ang, A.; Timmermann, A.", 2012, "Regime Changes and Financial Markets", "Annual Review of Financial Economics 4:313-337", "Survey", "Factor timing & regimes", 3,
  "Survey of regime-switching models in finance.", "Regime background."),
S("HAM1989", "Hamilton, J.D.", 1989, "A New Approach to the Economic Analysis of Nonstationary Time Series and the Business Cycle", "Econometrica 57(2):357-384", "Econometrics general", "Factor timing & regimes", 2,
  "Markov-switching model.", "Regime-detection baseline."),
S("GT2007", "Guidolin, M.; Timmermann, A.", 2007, "Asset Allocation under Multivariate Regime Switching", "Journal of Economic Dynamics and Control 31(11):3503-3544", "T2 Quant/Field", "Factor timing & regimes", 2,
  "Four-state regime model changes optimal allocations materially.", "Regime allocation baseline."),
S("NML2018", "Nystrup, P.; Madsen, H.; Lindstrom, E.", 2018, "Dynamic Portfolio Optimization across Hidden Market Regimes", "Quantitative Finance 18(1):83-95", "T2 Quant/Field", "Factor timing & regimes", 3,
  "HMM regime inference combined with model predictive control improves dynamic allocation.", "Regime + MPC template. [verify details]"),
S("KPT2012", "Kritzman, M.; Page, S.; Turkington, D.", 2012, "Regime Shifts: Implications for Dynamic Strategies", "Financial Analysts Journal 68(3):22-39", "T3 Practitioner", "Factor timing & regimes", 2,
  "Markov-switching regimes for turbulence, inflation and growth guide tactical allocation.", "Practitioner regime framing."),
S("SYM2025", "Shu, Y.; Yu, C.; Mulvey, J.M.", 2025, "Dynamic Asset Allocation with Asset-Specific Regime Forecasts", "Annals of Operations Research 346(1):285-318", "T2 Quant/Field", "Factor timing & regimes", 3,
  "Statistical jump models label regimes; gradient-boosted classifiers forecast them; forecasts feed mean-variance allocation.", "Regime-forecast module template."),
S("BAMS2014", "Bae, G.I.; Kim, W.C.; Mulvey, J.M.", 2014, "Dynamic Asset Allocation for Varied Financial Markets under Regime Switching Framework", "European Journal of Operational Research 234(2):450-458", "T2 Quant/Field", "Factor timing & regimes", 2,
  "Regime-switching framework for dynamic asset allocation.", "OR regime reference. [verify]"),
S("WG2008", "Welch, I.; Goyal, A.", 2008, "A Comprehensive Look at the Empirical Performance of Equity Premium Prediction", "Review of Financial Studies 21(4):1455-1508", "T1 General Finance", "Factor timing & regimes", 3,
  "Most predictors fail out of sample versus the historical mean.", "State-variable source; OOS discipline."),
S("CT2008", "Campbell, J.Y.; Thompson, S.B.", 2008, "Predicting Excess Stock Returns Out of Sample: Can Anything Beat the Historical Average?", "Review of Financial Studies 21(4):1509-1531", "T1 General Finance", "Factor timing & regimes", 2,
  "Weak restrictions on forecasts restore small but economically meaningful OOS predictability.", "Economic restrictions on forecasts."),
S("KP2015", "Kelly, B.; Pruitt, S.", 2015, "The Three-Pass Regression Filter: A New Approach to Forecasting Using Many Predictors", "Journal of Econometrics 186(2):294-316", "T2 Quant/Field", "ML asset pricing", 2,
  "3PRF (PLS generalisation) for forecasting with many predictors.", "State-variable aggregation method."),
# ---------------- Portfolio construction ----------------
S("MARK1952", "Markowitz, H.", 1952, "Portfolio Selection", "Journal of Finance 7(1):77-91", "T1 General Finance", "Portfolio construction", 3,
  "Mean-variance portfolio theory.", "Optimizer foundation."),
S("DGU2009", "DeMiguel, V.; Garlappi, L.; Uppal, R.", 2009, "Optimal Versus Naive Diversification: How Inefficient Is the 1/N Portfolio Strategy?", "Review of Financial Studies 22(5):1915-1953", "T1 General Finance", "Portfolio construction", 4,
  "None of 14 optimisation models consistently beats 1/N out of sample in Sharpe, CEQ or turnover.", "Naive benchmark is mandatory.", doi="10.1093/rfs/hhm075"),
S("LW2017", "Ledoit, O.; Wolf, M.", 2017, "Nonlinear Shrinkage of the Covariance Matrix for Portfolio Selection: Markowitz Meets Goldilocks", "Review of Financial Studies 30(12):4349-4388", "T1 General Finance", "Portfolio construction", 4,
  "Nonlinear shrinkage covariance estimator improves large-dimensional portfolio selection.", "Default covariance estimator.", doi="10.1093/rfs/hhx052"),
S("LW2004", "Ledoit, O.; Wolf, M.", 2004, "Honey, I Shrunk the Sample Covariance Matrix", "Journal of Portfolio Management 30(4):110-119", "T3 Practitioner", "Portfolio construction", 3,
  "Linear shrinkage toward constant correlation.", "Covariance robustness check."),
S("LDP2016", "Lopez de Prado, M.", 2016, "Building Diversified Portfolios that Outperform Out of Sample", "Journal of Portfolio Management 42(4):59-69", "T3 Practitioner", "Portfolio construction", 3,
  "Hierarchical Risk Parity avoids covariance inversion instability.", "Hierarchical benchmark.", doi="10.3905/jpm.2016.42.4.059"),
S("BL1992", "Black, F.; Litterman, R.", 1992, "Global Portfolio Optimization", "Financial Analysts Journal 48(5):28-43", "T3 Practitioner", "Portfolio construction", 3,
  "Blends equilibrium returns with investor views.", "Framework for blending ML alpha with confidence."),
S("MRT2010", "Maillard, S.; Roncalli, T.; Teiletche, J.", 2010, "The Properties of Equally Weighted Risk Contribution Portfolios", "Journal of Portfolio Management 36(4):60-70", "T3 Practitioner", "Portfolio construction", 2,
  "Equal-risk-contribution portfolios lie between minimum variance and 1/N.", "Risk-parity benchmark."),
S("CC2008", "Choueifaty, Y.; Coignard, Y.", 2008, "Toward Maximum Diversification", "Journal of Portfolio Management 35(1):40-51", "T3 Practitioner", "Portfolio construction", 2,
  "Maximum diversification portfolio.", "Diversification benchmark."),
S("RU2000", "Rockafellar, R.T.; Uryasev, S.", 2000, "Optimization of Conditional Value-at-Risk", "Journal of Risk 2(3):21-41", "T2 Quant/Field", "Portfolio construction", 2,
  "Linear-programming formulation for CVaR optimisation.", "Tail-risk optimiser variant."),
S("GI2003", "Goldfarb, D.; Iyengar, G.", 2003, "Robust Portfolio Selection Problems", "Mathematics of Operations Research 28(1):1-38", "T1b Finance/OR", "Portfolio construction", 3,
  "Robust counterparts of mean-variance problems as SOCPs.", "Uncertainty-set optimiser."),
S("DY2010", "Delage, E.; Ye, Y.", 2010, "Distributionally Robust Optimization under Moment Uncertainty with Application to Data-Driven Problems", "Operations Research 58(3):595-612", "T1b Finance/OR", "Portfolio construction", 2,
  "DRO with moment-based ambiguity sets.", "DRO foundation."),
S("BCZ2022", "Blanchet, J.; Chen, L.; Zhou, X.Y.", 2022, "Distributionally Robust Mean-Variance Portfolio Selection with Wasserstein Distances", "Management Science 68(9):6382-6410", "T1b Finance/OR", "Portfolio construction", 3,
  "Wasserstein DRO mean-variance with data-driven calibration of the ambiguity radius.", "DRO optimiser variant."),
S("KO2012", "Kirby, C.; Ostdiek, B.", 2012, "It's All in the Timing: Simple Active Portfolio Strategies that Outperform Naive Diversification", "Journal of Financial and Quantitative Analysis 47(2):437-467", "T1b Finance/OR", "Portfolio construction", 3,
  "Volatility-timing and reward-to-risk timing beat 1/N with low turnover, net of costs.", "Low-turnover timing benchmark."),
S("JM2003", "Jagannathan, R.; Ma, T.", 2003, "Risk Reduction in Large Portfolios: Why Imposing the Wrong Constraints Helps", "Journal of Finance 58(4):1651-1683", "T1 General Finance", "Portfolio construction", 3,
  "No-short-sale constraints act like covariance shrinkage.", "Constraints as regularisation."),
S("KZ2007", "Kan, R.; Zhou, G.", 2007, "Optimal Portfolio Choice with Parameter Uncertainty", "Journal of Financial and Quantitative Analysis 42(3):621-656", "T1b Finance/OR", "Portfolio construction", 3,
  "Combining tangency and minimum-variance portfolios reduces estimation-risk losses.", "Estimation-risk-aware baseline."),
S("CSS2012", "Ceria, S.; Saxena, A.; Stubbs, R.A.", 2012, "Factor Alignment Problems and Quantitative Portfolio Management", "Journal of Portfolio Management 38(2):29-43", "T3 Practitioner", "Portfolio construction", 4,
  "Misalignment between alpha model, risk model and constraints creates unintended exposures and risk underestimation.", "Alignment diagnostics for ML alpha."),
S("LS2008", "Lee, J.-H.; Stefek, D.", 2008, "Do Risk Factors Eat Alphas?", "Journal of Portfolio Management 34(4):12-25", "T3 Practitioner", "Portfolio construction", 3,
  "Discrepancies between risk and alpha factors create unintended exposures; alignment can help even at the expense of risk forecasts.", "Alignment diagnostics."),
# ---------------- End-to-end / decision-focused ----------------
S("EG2022", "Elmachtoub, A.N.; Grigas, P.", 2022, "Smart 'Predict, then Optimize'", "Management Science 68(1):9-26", "T1b Finance/OR", "End-to-end / decision-focused", 4,
  "SPO+ loss trains predictors on decision regret rather than prediction error.", "Decision-focused loss foundation."),
S("DAK2017", "Donti, P.L.; Amos, B.; Kolter, J.Z.", 2017, "Task-based End-to-end Model Learning in Stochastic Optimization", "Advances in Neural Information Processing Systems 30", "ML venue", "End-to-end / decision-focused", 3,
  "Learn probabilistic models by differentiating through the downstream optimisation task.", "End-to-end foundation. [DOI not in Crossref]"),
S("AK2017", "Amos, B.; Kolter, J.Z.", 2017, "OptNet: Differentiable Optimization as a Layer in Neural Networks", "Proceedings of ICML 2017 (PMLR 70)", "ML venue", "End-to-end / decision-focused", 3,
  "Differentiable quadratic-programming layers.", "Implementation of differentiable optimiser. [DOI not in Crossref]"),
S("AAB2019", "Agrawal, A.; Amos, B.; Barratt, S.; Boyd, S.; Diamond, S.; Kolter, J.Z.", 2019, "Differentiable Convex Optimization Layers", "Advances in Neural Information Processing Systems 32", "ML venue", "End-to-end / decision-focused", 3,
  "cvxpylayers: differentiate through disciplined convex programs.", "Tooling for cost-aware differentiable optimiser. [DOI not in Crossref]"),
S("BK2023", "Butler, A.; Kwon, R.H.", 2023, "Integrating Prediction in Mean-Variance Portfolio Optimization", "Quantitative Finance 23(3):429-452", "T2 Quant/Field", "End-to-end / decision-focused", 4,
  "Integrated prediction-optimisation (IPO) with closed forms for unconstrained MVO and differentiable QP layers otherwise; lower realised cost than predict-then-optimize.", "Decision-focused MVO benchmark.", doi="10.1080/14697688.2022.2162432"),
S("CI2023", "Costa, G.; Iyengar, G.N.", 2023, "Distributionally Robust End-to-End Portfolio Construction", "Quantitative Finance 23(10):1465-1482", "T2 Quant/Field", "End-to-end / decision-focused", 3,
  "End-to-end system with a DRO layer that learns robustness parameters.", "Robust end-to-end benchmark. [verify pages]", doi="10.1080/14697688.2023.2236148"),
S("ULM2024", "Uysal, A.S.; Li, X.; Mulvey, J.M.", 2024, "End-to-End Risk Budgeting Portfolio Optimization with Neural Networks", "Annals of Operations Research 339(1-2):397-426", "T2 Quant/Field", "End-to-end / decision-focused", 3,
  "Model-based network with risk-budgeting implicit layer; ETF out-of-sample 2017-2021 Sharpe 1.16 vs 0.83 for pure risk budgeting.", "Small-universe end-to-end evidence.", doi="10.1007/s10479-023-05539-4"),
S("ZZR2020", "Zhang, Z.; Zohren, S.; Roberts, S.", 2020, "Deep Learning for Portfolio Optimization", "Journal of Financial Data Science 2(4):8-20", "T3 Practitioner", "End-to-end / decision-focused", 2,
  "LSTM directly maximises portfolio Sharpe on market-index ETFs; best performance 2011-April 2020.", "Small-universe direct optimisation."),
S("CTWZ2021", "Cong, L.W.; Tang, K.; Wang, J.; Zhang, Y.", 2021, "AlphaPortfolio: Direct Construction through Deep Reinforcement Learning and Interpretable AI", "Working paper (SSRN 3554486; NBER w35195)", "WP", "End-to-end / decision-focused", 4,
  "Transformer-based RL directly optimises investor objectives; out-of-sample Sharpe above 2 and 13%+ alpha with monthly rebalancing in US equities, robust to excluding small/illiquid stocks; 'economic distillation' for interpretation.", "Direct-construction benchmark; implementability claims need independent replication [inference]."),
S("LZR2019", "Lim, B.; Zohren, S.; Roberts, S.", 2019, "Enhancing Time-Series Momentum Strategies Using Deep Neural Networks", "Journal of Financial Data Science 1(4):19-38", "T3 Practitioner", "End-to-end / decision-focused", 2,
  "Deep momentum networks trained on Sharpe loss with turnover regularisation.", "Sharpe-loss training with turnover penalty.", doi="10.3905/jfds.2019.1.015"),
S("WGRZ2022", "Wood, K.; Giegerich, S.; Roberts, S.; Zohren, S.", 2022, "Trading with the Momentum Transformer: An Intelligent and Interpretable Architecture", "arXiv 2112.08534 [verify journal version]", "WP", "End-to-end / decision-focused", 2,
  "Attention-based architecture for time-series momentum with interpretable attention patterns and regime adaptation.", "Attention interpretability example."),
S("MS2001", "Moody, J.; Saffell, M.", 2001, "Learning to Trade via Direct Reinforcement", "IEEE Transactions on Neural Networks 12(4):875-889", "ML venue", "End-to-end / decision-focused", 2,
  "Recurrent reinforcement learning optimises differential Sharpe ratio with costs.", "Historical RL foundation.", doi="10.1109/72.935097"),
S("FK2018", "Fischer, T.; Krauss, C.", 2018, "Deep Learning with Long Short-Term Memory Networks for Financial Market Predictions", "European Journal of Operational Research 270(2):654-669", "T2 Quant/Field", "ML strategies & implementability", 2,
  "LSTM for S&P 500 constituent direction prediction outperforms memory-free methods; profitability declines in recent years [verify magnitude].", "Daily stat-arb evidence.", doi="10.1016/j.ejor.2017.11.054"),
S("KDH2017", "Krauss, C.; Do, X.A.; Huck, N.", 2017, "Deep Neural Networks, Gradient-Boosted Trees, Random Forests: Statistical Arbitrage on the S&P 500", "European Journal of Operational Research 259(2):689-702", "T2 Quant/Field", "ML strategies & implementability", 2,
  "Ensemble of DNN, GBT and RF for daily S&P 500 stat-arb; returns decline over time and after costs [verify].", "Ensemble evidence.", doi="10.1016/j.ejor.2016.10.031"),
# ---------------- Transaction costs & microstructure ----------------
S("DNMV2023", "Detzel, A.; Novy-Marx, R.; Velikov, M.", 2023, "Model Comparison with Transaction Costs", "Journal of Finance 78(3):1743-1775", "T1 General Finance", "TC & implementability", 3,
  "Ignoring costs biases model comparison toward high-cost factors; net of costs FF5 beats q-factor and six-factor models.", "Net-of-cost alpha benchmark choice.", doi="10.1111/jofi.13225"),
S("PW2020", "Patton, A.J.; Weller, B.M.", 2020, "What You See Is Not What You Get: The Costs of Trading Market Anomalies", "Journal of Financial Economics 137(2):515-549", "T1 General Finance", "TC & implementability", 3,
  "Infers implementation costs of anomalies from real-world fund returns relative to paper portfolios [verify magnitudes].", "Cost-calibration cross-check."),
S("KS2004", "Korajczyk, R.A.; Sadka, R.", 2004, "Are Momentum Profits Robust to Trading Costs?", "Journal of Finance 59(3):1039-1082", "T1 General Finance", "TC & implementability", 3,
  "Price-impact-based capacity estimates for momentum; liquidity-weighted strategies have higher capacity.", "Capacity methodology."),
S("LSZ2004", "Lesmond, D.A.; Schill, M.J.; Zhou, C.", 2004, "The Illusory Nature of Momentum Profits", "Journal of Financial Economics 71(2):349-380", "T1 General Finance", "TC & implementability", 2,
  "Momentum concentrated in high-cost stocks; profits illusory after costs.", "Cost pessimism reference."),
S("HAS2009", "Hasbrouck, J.", 2009, "Trading Costs and Returns for U.S. Equities: Estimating Effective Costs from Daily Data", "Journal of Finance 64(3):1445-1477", "T1 General Finance", "TC & implementability", 4,
  "Gibbs-sampler estimate of effective costs from daily prices, validated against TAQ.", "Historical spread estimator.", doi="10.1111/j.1540-6261.2009.01469.x"),
S("CS2012", "Corwin, S.A.; Schultz, P.", 2012, "A Simple Way to Estimate Bid-Ask Spreads from Daily High and Low Prices", "Journal of Finance 67(2):719-760", "T1 General Finance", "TC & implementability", 3,
  "High-low spread estimator.", "Low-frequency spread estimator.", doi="10.1111/j.1540-6261.2012.01729.x"),
S("AR2017", "Abdi, F.; Ranaldo, A.", 2017, "A Simple Estimation of Bid-Ask Spreads from Daily Close, High, and Low Prices", "Review of Financial Studies 30(12):4437-4480", "T1 General Finance", "TC & implementability", 3,
  "Close-high-low estimator with high correlation to TAQ effective spreads.", "Low-frequency spread estimator."),
S("AGK2024", "Ardia, D.; Guidotti, E.; Kroencke, T.A.", 2024, "Efficient Estimation of Bid-Ask Spreads from Open, High, Low, and Close Prices", "Journal of Financial Economics 161:103916", "T1 General Finance", "TC & implementability", 4,
  "EDGE estimator from OHLC prices; R package 'bidask'.", "Preferred low-frequency spread estimator where TAQ unavailable. [verify volume]"),
S("AMI2002", "Amihud, Y.", 2002, "Illiquidity and Stock Returns: Cross-Section and Time-Series Effects", "Journal of Financial Markets 5(1):31-56", "T2 Quant/Field", "TC & implementability", 3,
  "Illiquidity ratio; market illiquidity predicts returns.", "Liquidity feature and state variable."),
S("KYO2016", "Kyle, A.S.; Obizhaeva, A.A.", 2016, "Market Microstructure Invariance: Empirical Hypotheses", "Econometrica 84(4):1345-1404", "Econometrics general", "TC & implementability", 3,
  "Invariance hypotheses imply scaling laws for bet sizes and transaction costs.", "Market-impact functional form."),
S("AC2001", "Almgren, R.; Chriss, N.", 2001, "Optimal Execution of Portfolio Transactions", "Journal of Risk 3(2):5-39", "T2 Quant/Field", "TC & implementability", 3,
  "Mean-variance optimal execution with temporary and permanent impact.", "Execution-cost model."),
S("ATHL2005", "Almgren, R.; Thum, C.; Hauptmann, E.; Li, H.", 2005, "Direct Estimation of Equity Market Impact", "Risk 18(7):58-62", "T3 Practitioner", "TC & implementability", 3,
  "Empirical market-impact estimates from institutional orders support concave (approximately 3/5 power) temporary impact [verify exponent].", "Impact calibration."),
S("NMV2019", "Novy-Marx, R.; Velikov, M.", 2019, "Comparing Cost-Mitigation Techniques", "Financial Analysts Journal 75(1):85-102", "T3 Practitioner", "TC & implementability", 3,
  "Compares banding, staggering, and other cost-mitigation methods.", "Heuristic mitigation benchmarks."),
S("SHU1997", "Shumway, T.", 1997, "The Delisting Bias in CRSP Data", "Journal of Finance 52(1):327-340", "T1 General Finance", "Data & measurement", 4,
  "Missing performance-related delisting returns bias CRSP returns upward.", "Delisting-return correction."),
S("BLLP2025", "Bryzgalova, S.; Lerner, S.; Lettau, M.; Pelger, M.", 2025, "Missing Financial Data", "Review of Financial Studies 38(3):803-882", "T1 General Finance", "Data & measurement", 4,
  "Characteristics are frequently missing, not at random; proposes cross-sectional and time-series imputation. [verify pages]", "Missing-data handling protocol."),
S("FHNW2025", "Freyberger, J.; Hoppner, B.; Neuhierl, A.; Weber, M.", 2025, "Missing Data in Asset Pricing Panels", "Review of Financial Studies 38(3):760-802", "T1 General Finance", "Data & measurement", 4,
  "Generalised method of moments approach to missing characteristics; imputation choices affect results. [verify pages]", "Missing-data handling protocol."),
# ---------------- Statistical inference & backtest integrity ----------------
S("NW1987", "Newey, W.K.; West, K.D.", 1987, "A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix", "Econometrica 55(3):703-708", "Econometrics general", "Statistical inference", 4,
  "HAC standard errors.", "Mean-return and alpha t-statistics."),
S("LO2002", "Lo, A.W.", 2002, "The Statistics of Sharpe Ratios", "Financial Analysts Journal 58(4):36-52", "T3 Practitioner", "Statistical inference", 4,
  "Sampling distribution of Sharpe ratios under serial correlation; annualisation errors.", "Sharpe inference."),
S("LW2008", "Ledoit, O.; Wolf, M.", 2008, "Robust Performance Hypothesis Testing with the Sharpe Ratio", "Journal of Empirical Finance 15(5):850-859", "T2 Quant/Field", "Statistical inference", 5,
  "HAC and studentised circular block bootstrap tests for Sharpe-ratio differences.", "Primary Sharpe-difference test."),
S("JK1981", "Jobson, J.D.; Korkie, B.M.", 1981, "Performance Hypothesis Testing with the Sharpe and Treynor Measures", "Journal of Finance 36(4):889-908", "T1 General Finance", "Statistical inference", 3,
  "Asymptotic test for Sharpe-ratio equality (later corrected by Memmel 2003).", "Classical Sharpe test."),
S("WHI2000", "White, H.", 2000, "A Reality Check for Data Snooping", "Econometrica 68(5):1097-1126", "Econometrics general", "Statistical inference", 5,
  "Bootstrap test that the best of many models does not beat a benchmark.", "Data-snooping control.", doi="10.1111/1468-0262.00152"),
S("HAN2005", "Hansen, P.R.", 2005, "A Test for Superior Predictive Ability", "Journal of Business & Economic Statistics 23(4):365-380", "T2 Quant/Field", "Statistical inference", 5,
  "SPA test: more powerful and less sensitive to poor alternatives than the Reality Check.", "Primary data-snooping test.", doi="10.1198/073500105000000063"),
S("RW2005", "Romano, J.P.; Wolf, M.", 2005, "Stepwise Multiple Testing as Formalized Data Snooping", "Econometrica 73(4):1237-1282", "Econometrics general", "Statistical inference", 4,
  "StepM identifies which models beat the benchmark with FWER control.", "Which cells beat the benchmark."),
S("HLN2011", "Hansen, P.R.; Lunde, A.; Nason, J.M.", 2011, "The Model Confidence Set", "Econometrica 79(2):453-497", "Econometrics general", "Statistical inference", 4,
  "Set of models containing the best with given confidence.", "Report the MCS of design cells."),
S("DM1995", "Diebold, F.X.; Mariano, R.S.", 1995, "Comparing Predictive Accuracy", "Journal of Business & Economic Statistics 13(3):253-263", "T2 Quant/Field", "Statistical inference", 4,
  "Test of equal predictive accuracy.", "Forecast comparison."),
S("CW2007", "Clark, T.E.; West, K.D.", 2007, "Approximately Normal Tests for Equal Predictive Accuracy in Nested Models", "Journal of Econometrics 138(1):291-311", "T2 Quant/Field", "Statistical inference", 4,
  "Adjusted MSPE test for nested models.", "Nested model comparisons (static vs conditional)."),
S("PR1994", "Politis, D.N.; Romano, J.P.", 1994, "The Stationary Bootstrap", "Journal of the American Statistical Association 89(428):1303-1313", "Econometrics general", "Statistical inference", 4,
  "Random-block bootstrap for stationary dependent data.", "Bootstrap for SPA/RC."),
S("BBLZ2017", "Bailey, D.H.; Borwein, J.; Lopez de Prado, M.; Zhu, Q.J.", 2017, "The Probability of Backtest Overfitting", "Journal of Computational Finance 20(4):39-69", "T2 Quant/Field", "Statistical inference", 5,
  "CSCV estimates the probability that the in-sample best configuration underperforms out of sample.", "PBO reporting.", doi="10.21314/JCF.2016.322"),
S("HL2015", "Harvey, C.R.; Liu, Y.", 2015, "Backtesting", "Journal of Portfolio Management 42(1):13-28", "T3 Practitioner", "Statistical inference", 4,
  "Sharpe-ratio haircuts for multiple testing.", "Haircut Sharpe reporting."),
S("AHM2019", "Arnott, R.; Harvey, C.R.; Markowitz, H.", 2019, "A Backtesting Protocol in the Era of Machine Learning", "Journal of Financial Data Science 1(1):64-74", "T3 Practitioner", "Statistical inference", 5,
  "Checklist-style protocol for credible ML backtests.", "Basis for reviewer-proof checklist."),
S("FM1973", "Fama, E.F.; MacBeth, J.D.", 1973, "Risk, Return, and Equilibrium: Empirical Tests", "Journal of Political Economy 81(3):607-636", "T1 General Finance", "Statistical inference", 3,
  "Two-pass cross-sectional regression methodology.", "FM combination benchmark and inference."),
S("BH1995", "Benjamini, Y.; Hochberg, Y.", 1995, "Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing", "Journal of the Royal Statistical Society Series B 57(1):289-300", "Econometrics general", "Statistical inference", 3,
  "FDR control procedure.", "Signal-level multiple testing."),
S("LDP2018", "Lopez de Prado, M.", 2018, "Advances in Financial Machine Learning", "Wiley (book)", "Book", "Statistical inference", 4,
  "Purged k-fold cross-validation with embargo, meta-labelling, backtest overfitting.", "Validation protocol for overlapping labels."),
# ---------------- ML methods & interpretability ----------------
S("LL2017", "Lundberg, S.M.; Lee, S.-I.", 2017, "A Unified Approach to Interpreting Model Predictions", "Advances in Neural Information Processing Systems 30", "ML venue", "ML methods", 4,
  "SHAP values unify additive feature attribution methods.", "Signal attribution."),
S("AZ2020", "Apley, D.W.; Zhu, J.", 2020, "Visualizing the Effects of Predictor Variables in Black Box Supervised Learning Models", "Journal of the Royal Statistical Society Series B 82(4):1059-1086", "Econometrics general", "ML methods", 3,
  "Accumulated local effects plots robust to correlated predictors.", "Preferred over PDP with correlated signals."),
S("FRI2001", "Friedman, J.H.", 2001, "Greedy Function Approximation: A Gradient Boosting Machine", "Annals of Statistics 29(5):1189-1232", "Econometrics general", "ML methods", 3,
  "Gradient boosting; partial dependence plots.", "GBDT foundation."),
S("BRE2001", "Breiman, L.", 2001, "Random Forests", "Machine Learning 45(1):5-32", "ML venue", "ML methods", 3, "Random forests.", "RF baseline."),
S("CG2016", "Chen, T.; Guestrin, C.", 2016, "XGBoost: A Scalable Tree Boosting System", "Proceedings of ACM SIGKDD 2016", "ML venue", "ML methods", 3, "Scalable regularised gradient boosting.", "GBDT implementation."),
S("KE2017", "Ke, G.; et al.", 2017, "LightGBM: A Highly Efficient Gradient Boosting Decision Tree", "Advances in Neural Information Processing Systems 30", "ML venue", "ML methods", 3, "Histogram-based efficient GBDT.", "Primary GBDT implementation."),
S("TIB1996", "Tibshirani, R.", 1996, "Regression Shrinkage and Selection via the Lasso", "Journal of the Royal Statistical Society Series B 58(1):267-288", "Econometrics general", "ML methods", 2, "LASSO.", "Linear sparse baseline."),
S("ZH2005", "Zou, H.; Hastie, T.", 2005, "Regularization and Variable Selection via the Elastic Net", "Journal of the Royal Statistical Society Series B 67(2):301-320", "Econometrics general", "ML methods", 2, "Elastic net.", "Linear baseline."),
S("VAS2017", "Vaswani, A.; et al.", 2017, "Attention Is All You Need", "Advances in Neural Information Processing Systems 30", "ML venue", "ML methods", 2, "Transformer architecture.", "Attention models."),
S("HS1997", "Hochreiter, S.; Schmidhuber, J.", 1997, "Long Short-Term Memory", "Neural Computation 9(8):1735-1780", "ML venue", "ML methods", 2, "LSTM.", "Recurrent baseline."),
S("LPB2017", "Lakshminarayanan, B.; Pritzel, A.; Blundell, C.", 2017, "Simple and Scalable Predictive Uncertainty Estimation Using Deep Ensembles", "Advances in Neural Information Processing Systems 30", "ML venue", "ML methods", 4, "Deep ensembles give calibrated predictive uncertainty.", "Uncertainty estimator."),
S("GG2016", "Gal, Y.; Ghahramani, Z.", 2016, "Dropout as a Bayesian Approximation: Representing Model Uncertainty in Deep Learning", "Proceedings of ICML 2016 (PMLR 48)", "ML venue", "ML methods", 3, "MC dropout approximates Bayesian uncertainty.", "Uncertainty estimator alternative."),
S("JJNH1991", "Jacobs, R.A.; Jordan, M.I.; Nowlan, S.J.; Hinton, G.E.", 1991, "Adaptive Mixtures of Local Experts", "Neural Computation 3(1):79-87", "ML venue", "ML methods", 3, "Mixture-of-experts with gating network.", "Regime-gated combination architecture."),
S("FAL2017", "Finn, C.; Abbeel, P.; Levine, S.", 2017, "Model-Agnostic Meta-Learning for Fast Adaptation of Deep Networks", "Proceedings of ICML 2017 (PMLR 70)", "ML venue", "ML methods", 2, "MAML meta-learning.", "Adaptive-learning option."),
S("HTF2009", "Hastie, T.; Tibshirani, R.; Friedman, J.", 2009, "The Elements of Statistical Learning (2nd ed.)", "Springer (book)", "Book", "ML methods", 2, "Statistical learning reference.", "Methods reference."),
S("GRIN1989", "Grinold, R.C.", 1989, "The Fundamental Law of Active Management", "Journal of Portfolio Management 15(3):30-37", "T3 Practitioner", "Portfolio construction", 4, "IR approximately IC x sqrt(breadth).", "Links IC to IR; motivates IC-weighting baseline."),
S("GK2000", "Grinold, R.C.; Kahn, R.N.", 2000, "Active Portfolio Management (2nd ed.)", "McGraw-Hill (book)", "Book", "Portfolio construction", 4, "Alpha forecasting, signal combination and portfolio construction for quantitative managers.", "Practitioner combination canon."),
S("NAG2021", "Nagel, S.", 2021, "Machine Learning in Asset Pricing", "Princeton University Press (book)", "Book", "ML asset pricing", 3, "Monograph on ML methods in asset pricing and their economic restrictions.", "Background monograph."),

# ---------------- 2025-2026 frontier (added Sep 2026 after the design v2 search) ----------------
S("FRLUX2025", "Zhang, J.", 2025, "FR-LUX: Friction-Aware, Regime-Conditioned Policy Optimization for Implementable Portfolio Management", "Working paper (arXiv 2510.02986)", "WP", "Factor timing & regimes", 5,
  "Reinforcement-learning policy with proportional and impact costs inside the reward, inaction bands, conditioning on four volatility-liquidity regimes; evaluated on a regime x cost grid with bootstrap CIs and multiple-testing corrections; reports a flatter cost-performance slope than baselines.",
  "Closest new prior art for the conditioning x cost interaction (gap G2); cite and differentiate (single method vs factorial attribution; small asset space vs ~150-signal cross-section)."),
S("VSC2026", "Afsharhajari, N.; Li, J.Y.-M.", 2026, "The Virtue of Sparsity in Complexity", "Working paper (arXiv 2604.17166)", "WP", "ML asset pricing", 4,
  "Distinguishes capacity sparsity from factor sparsity; with nonlinear feature expansions, basis-pursuit sparse selection keeps improving in the high-complexity regime while the dense ridgeless benchmark plateaus.",
  "Motivates the dense/sparse arms of our complexity ladder (levels A2/A3)."),
S("AIPT2025", "Kelly, B.; et al.", 2025, "APT or AIPT? The Surprising Dominance of Large Factor Models", "Working paper (EDHEC-hosted PDF, Oct 2025) [verify authors and venue]", "WP", "ML asset pricing", 3,
  "Whether extra factors help depends on the eigenvalue distribution: concentrated spectra show no virtue of complexity, diffuse ones do.",
  "Basis for our spectrum diagnostic, which predicts when the complexity rung should pay."),
S("SPUR2026", "[verify authors]", 2026, "Spurious Predictability in Financial Machine Learning", "Working paper (arXiv 2604.15531)", "WP", "Statistical inference", 5,
  "Adaptive specification search produces statistically significant backtests under martingale-difference nulls; proposes a falsification audit with zero-predictability reference classes, microstructure placebos and a multiplicity-adjusted inflation gap.",
  "Adopted as our credibility layer; raises the bar that competing submissions must clear."),
S("LLG2025", "Chen, Z.; Kelly, B.; Malamud, S.", 2025, "Limits To (Machine) Learning", "Working paper (arXiv 2512.12735)", "WP", "ML asset pricing", 3,
  "Defines a limits-to-learning gap: a lower bound on the discrepancy between empirical fit and the population benchmark, implying standard ML understates true predictability.",
  "Cited when interpreting small R2 and IC values."),
S("SPO2026", "Wang, Y.; Hasuike, T.", 2026, "Decision-Induced Ranking Explains Prediction Inflation and Excessive Turnover in SPO-Based Portfolio Optimization", "Working paper (arXiv 2605.01176)", "WP", "End-to-end / decision-focused", 4,
  "Shows decision-focused (SPO) portfolio learning inflates return signals and churns the book; proposes clipping, min-max rescaling and partial portfolio adjustment.",
  "Our economic-objective cells adopt these controls and report inflation as a diagnostic."),
S("CPPS2024", "Kato, M.", 2024, "Conformal Predictive Portfolio Selection", "Working paper (arXiv 2410.16333, revised 2025)", "WP", "Portfolio construction", 4,
  "Combines conformal prediction intervals with portfolio selection across AR, random-forest and neural-network forecasters.",
  "Basis for uncertainty level D2 (calibrated intervals) instead of raw ensemble dispersion."),
S("SERT2025", "Lai, S.", 2025, "Asset Pricing in Pre-trained Transformer", "Working paper (arXiv 2505.01575)", "WP", "ML asset pricing", 3,
  "Transformer variants for US large-cap pricing across pre-pandemic, pandemic and post-pandemic periods; reports high out-of-sample R2 during turbulent markets.",
  "Context for our cross-sectional attention rung (level A4); look-ahead handling is not documented in the abstract [verify]."),
S("FMYY2025", "Fan, Q.; Medeiros, M.C.; Yang, H.; Yang, S.", 2025, "Cost-aware Portfolios in a Large Universe of Assets", "Working paper (arXiv 2412.11575, revised Aug 2025)", "WP", "Portfolio construction", 3,
  "Mean-variance rebalancing with nonconvex penalties under proportional and quadratic transaction costs in high dimensions; S&P 500 and Russell 2000 evidence.",
  "Alternative cost-aware optimiser to cite alongside ours."),
S("RR2007", "Rahimi, A.; Recht, B.", 2007, "Random Features for Large-Scale Kernel Machines", "Advances in Neural Information Processing Systems 20", "ML venue", "ML methods", 3,
  "Random Fourier features approximate shift-invariant kernels with an explicit finite-dimensional map.",
  "The feature map underlying our complexity ladder and the virtue-of-complexity literature."),
]
