# -*- coding: utf-8 -*-
"""After-tax investing and online/adaptive learning (added Sep 2026).

Two literatures the project needs once the evaluation target became "net profit out of sample after
costs AND taxes, with models that adapt on their own":

1. **After-tax equity investing.** Well developed, and entirely separate from the ML asset-pricing
   literature. No paper in either group does both, which is the opening.
2. **Prediction with expert advice / online portfolio selection.** Supplies the regret-bounded
   aggregation rule and the drift detector, so the adaptive layer cites a guarantee rather than
   claiming a novel algorithm.

Same evidence conventions as lit_core.py and lit_other.py. Entries marked [verify] have not yet been
confirmed against Crossref; the build's verification pass resolves them and flags anything unmatched.
"""

from lit_other import S

TAX_ONLINE = [
# ---------------- After-tax investing ----------------
S("JA1993", "Jeffrey, R.H.; Arnott, R.D.", 1993, "Is Your Alpha Big Enough to Cover Its Taxes?",
  "Journal of Portfolio Management 19(3):15-25", "T2 Quant/Field", "After-tax investing", 5,
  "Poses the central question: active management must clear the tax cost of realising gains, not only the trading cost; for a high-turnover taxable strategy the hurdle is large.",
  "The framing question of our after-tax layer. It poses the problem for active equity generally; it does not test machine-learning signal combination.",
  doi="10.3905/jpm.1993.710867"),
S("CON1983", "Constantinides, G.M.", 1983, "Capital Market Equilibrium with Personal Tax",
  "Econometrica 51(3):611-636", "T1 General/Econ", "After-tax investing", 4,
  "Derives the optimal realisation policy under a realisation-based capital-gains tax: realise losses immediately, defer gains indefinitely.",
  "Theoretical benchmark for our TAX_OPTIMAL lot rule; it is a policy result, not a measurement of an ML pipeline.",
  doi="10.2307/1912150"),
S("CON1984", "Constantinides, G.M.", 1984, "Optimal Stock Trading with Personal Taxes: Implications for Prices and the Abnormal January Returns",
  "Journal of Financial Economics 13(1):65-89", "T1 General Finance", "After-tax investing", 3,
  "Optimal tax trading with short- and long-term rates; links realisation incentives to seasonal return patterns.",
  "Source of the short/long holding-period incentive our optimiser's deferral term encodes.",
  doi="10.1016/0304-405X(84)90032-1"),
S("DSZ2001", "Dammon, R.M.; Spatt, C.S.; Zhang, H.H.", 2001, "Optimal Consumption and Investment with Capital Gains Taxes",
  "Review of Financial Studies 14(3):583-616", "T1 General Finance", "After-tax investing", 3,
  "Lifecycle portfolio choice when rebalancing triggers capital-gains tax; the embedded gain creates a lock-in that distorts the optimal portfolio.",
  "The lock-in mechanism our optimiser's gain penalty represents; lifecycle consumption, not cross-sectional signal combination.",
  doi="10.1093/rfs/14.3.583"),
S("DSZ2004", "Dammon, R.M.; Spatt, C.S.; Zhang, H.H.", 2004, "Optimal Asset Location and Allocation with Taxable and Tax-Deferred Investing",
  "Journal of Finance 59(3):999-1037", "T1 General Finance", "After-tax investing", 2,
  "Where to hold which asset across taxable and tax-deferred accounts.",
  "Account-location question, adjacent to ours; cited for completeness of the tax-investing map.",
  doi="10.1111/j.1540-6261.2004.00657.x"),
S("ABY2001", "Arnott, R.D.; Berkin, A.L.; Ye, J.", 2001, "Loss Harvesting: What's It Worth to the Taxable Investor?",
  "Journal of Wealth Management 3(4):10-18", "T3 Practitioner", "After-tax investing", 4,
  "Quantifies the value of systematic loss harvesting for a taxable equity investor; the benefit is front-loaded and decays as the portfolio's basis falls.",
  "The decay result matters for us: harvesting value is not a constant per-year number, so a short backtest overstates it. [verify]"),
S("BY2003", "Berkin, A.L.; Ye, J.", 2003, "Tax Management, Loss Harvesting, and HIFO Accounting",
  "Financial Analysts Journal 59(4):91-102", "T2 Quant/Field", "After-tax investing", 4,
  "Compares lot-accounting methods and shows HIFO materially improves after-tax outcomes relative to FIFO for a managed equity portfolio.",
  "Direct support for making lot selection a first-class axis rather than an implementation detail.",
  doi="10.2469/faj.v59.n4.2546"),
S("SS2018", "Sialm, C.; Sosner, N.", 2018, "Taxes, Shorting, and Active Management",
  "Financial Analysts Journal 74(1):88-107", "T2 Quant/Field", "After-tax investing", 5,
  "After-tax analysis of long/short factor strategies: shorting generates short-term gains (IRC s1233) but also a continuing supply of harvestable losses, so a long/short book can be more tax efficient than its gross turnover suggests.",
  "CLOSEST PRIOR ART for the after-tax layer. It analyses long/short FACTOR portfolios. We do not repeat it: our object is whether the after-tax ranking of ML COMBINATION DESIGNS differs from the net-of-cost ranking. Threat: HIGH.",
  doi="10.2469/faj.v74.n1.1"),
S("IM2012", "Israel, R.; Moskowitz, T.J.", 2012, "How Tax Efficient Are Equity Styles?",
  "Working paper (Chicago Booth Research Paper 12-20; NBER w18382)", "WP", "After-tax investing", 4,
  "After-tax returns of value, momentum and size; momentum's short holding period costs it far more tax than value's.",
  "Predicts the mechanism we test at the design level: holding-period composition, not turnover alone, drives the after-tax ranking."),
S("CBLO2020", "Chaudhuri, S.E.; Burnham, T.C.; Lo, A.W.", 2020, "An Empirical Evaluation of Tax-Loss-Harvesting Alpha",
  "Financial Analysts Journal 76(3):99-108", "T2 Quant/Field", "After-tax investing", 3,
  "Measures tax-loss-harvesting alpha across time and market conditions; the benefit is highly state-dependent and concentrated in volatile, down markets.",
  "State dependence of the tax benefit interacts with our conditioning axis; harvesting is their strategy, ours is a constraint on an alpha pipeline.",
  doi="10.1080/0015198X.2020.1760064"),

# ---------------- Online learning, regret, drift ----------------
S("VOVK1990", "Vovk, V.G.", 1990, "Aggregating Strategies", "Proceedings of the Third Annual Workshop on Computational Learning Theory (COLT):371-386", "ML venue", "Online learning", 4,
  "Introduces aggregation of expert predictions with a bound on the loss relative to the best expert.",
  "Origin of the rule our adaptive layer uses; cited, not claimed."),
S("LW1994", "Littlestone, N.; Warmuth, M.K.", 1994, "The Weighted Majority Algorithm",
  "Information and Computation 108(2):212-261", "ML venue", "Online learning", 4,
  "Multiplicative-weights aggregation with a mistake bound relative to the best expert in hindsight.",
  "The algorithm behind HedgeAggregator.",
  doi="10.1006/inco.1994.1009"),
S("FS1997", "Freund, Y.; Schapire, R.E.", 1997, "A Decision-Theoretic Generalization of On-Line Learning and an Application to Boosting",
  "Journal of Computer and System Sciences 55(1):119-139", "ML venue", "Online learning", 4,
  "Hedge and AdaBoost; O(sqrt(T log N)) regret against the best fixed expert.",
  "Source of the regret bound we report alongside every adaptive result.",
  doi="10.1006/jcss.1997.1504"),
S("HW1998", "Herbster, M.; Warmuth, M.K.", 1998, "Tracking the Best Expert",
  "Machine Learning 32(2):151-178", "ML venue", "Online learning", 5,
  "Fixed-share variant competes with the best SEQUENCE of experts, not merely the best fixed one, at the cost of a term in the number of switches.",
  "The right guarantee when the world has regimes; this is the rule that lets our combination switch models without a monthly specification search.",
  doi="10.1023/A:1007424614876"),
S("CESA2006", "Cesa-Bianchi, N.; Lugosi, G.", 2006, "Prediction, Learning, and Games",
  "Cambridge University Press (book)", "Book", "Online learning", 4,
  "Standard reference for prediction with expert advice and its regret analysis.",
  "Textbook source for the bounds we quote."),
S("HAZ2016", "Hazan, E.", 2016, "Introduction to Online Convex Optimization",
  "Foundations and Trends in Optimization 2(3-4):157-325", "ML venue", "Online learning", 3,
  "Unified treatment of online convex optimisation and its regret guarantees.",
  "Background for the online-gradient alternative we did not adopt.",
  doi="10.1561/2400000013"),
S("COVER1991", "Cover, T.M.", 1991, "Universal Portfolios", "Mathematical Finance 1(1):1-29", "T2 Quant/Field", "Online learning", 4,
  "A portfolio achieving the same asymptotic growth rate as the best constant-rebalanced portfolio chosen in hindsight, without knowing it in advance.",
  "The finance-side origin of regret-based adaptation. It aggregates over ASSETS; we aggregate over MODELS and score them after tax.",
  doi="10.1111/j.1467-9965.1991.tb00002.x"),
S("BK1999", "Blum, A.; Kalai, A.", 1999, "Universal Portfolios With and Without Transaction Costs",
  "Machine Learning 35(3):193-205", "ML venue", "Online learning", 4,
  "Extends universal portfolios to proportional transaction costs while preserving the guarantee.",
  "Precedent for putting costs inside a regret-bounded online rule; costs only, no tax.",
  doi="10.1023/A:1007530728748"),
S("LH2014", "Li, B.; Hoi, S.C.H.", 2014, "Online Portfolio Selection: A Survey",
  "ACM Computing Surveys 46(3):35", "ML venue", "Online learning", 3,
  "Survey of online portfolio selection: follow-the-winner, follow-the-loser, pattern matching and meta-learning families.",
  "Map of the online-portfolio field; confirms the aggregation-over-models framing is not the standard object there.",
  doi="10.1145/2512962"),
S("KS2024", "Krasner, S.; Sosner, N.", 2024, "Loss Harvesting or Gain Deferral? A Surprising Source of Tax Benefits of Tax-Aware Long-Short Strategies",
  "Journal of Wealth Management, Summer 2024 (SSRN 4584287)", "T3 Practitioner", "After-tax investing", 5,
  "Tax-aware long-short factor strategies can realise cumulative net capital losses exceeding 100% of initial capital within three years while still producing pre-tax alpha; the losses come mainly from DEFERRAL of short-term gains on longs, not from elevated loss harvesting. Tax awareness shifts exposure away from value and toward momentum, because deferring gains means holding recent winners and accelerating losses means selling recent losers.",
  "CRITICAL. This pre-empts the naive form of our after-tax mechanism claim: the value-to-momentum reordering under tax awareness is THEIR result (and Israel-Moskowitz's), not ours. We may only ask whether the same mechanism reorders ML DESIGN INGREDIENTS. Threat: HIGH. [verify: exact volume and pages]"),
S("SKP2018", "Sosner, N.; Krasner, S.; Pyne, T.", 2018, "The Tax Benefits of Relaxing the Long-Only Constraint: Do They Come from Character or Deferral?",
  "Working paper (SSRN 3264213)", "WP", "After-tax investing", 3,
  "Decomposes the tax benefit of relaxing the long-only constraint into character (s1233 short-term treatment) and deferral components.",
  "The character-versus-deferral decomposition we would otherwise have had to invent. Cite it. [verify]"),
S("G13030", "[verify authors]", 2024, "A Guide to 130/30 Loss Harvesting", "Journal of Asset Management 25:445-459", "T2 Quant/Field", "After-tax investing", 3,
  "Loss-harvesting mechanics for relaxed-constraint long-short equity portfolios.",
  "Implementation reference for the harvesting arm.", doi="10.1057/s41260-024-00374-z"),
S("RABM2023", "Remlinger, C.; Alasseur, C.; Briere, M.; Mikael, J.", 2023, "Expert Aggregation for Financial Forecasting",
  "The Journal of Finance and Data Science (arXiv 2111.15365; SSRN 4513503)", "T2 Quant/Field", "Online learning", 5,
  "Applies Bernstein Online Aggregation to combine individual stock return forecasts from several machine-learning models, and builds long-short strategies from the aggregate. The aggregation beats the individual algorithms on Sharpe and shortfall at similar turnover, including in non-stationary environments.",
  "CRITICAL and the closest prior art for our adaptive layer: aggregation over ML MODELS, stock-level long-short, regret-bounded, beats its members. Our adaptive layer is therefore a METHOD WE ADOPT, not a contribution. The only remaining difference is that our reward is realised AFTER-TAX net return and our experts are cells of a controlled factorial design. Threat: HIGH. Read the arXiv full text before writing any adaptive section."),
S("WINT2017", "Wintenberger, O.", 2017, "Optimal Learning with Bernstein Online Aggregation", "Machine Learning 106(1):119-141", "ML venue", "Online learning", 3,
  "Introduces Bernstein Online Aggregation, a second-order refinement of exponential weighting with improved regret.",
  "The algorithm used by RABM2023; stronger than the plain Hedge rule we implemented. [verify year, volume and pages]"),
S("PAGE1954", "Page, E.S.", 1954, "Continuous Inspection Schemes", "Biometrika 41(1/2):100-115", "T1 General/Stats", "Statistical inference", 3,
  "The CUSUM procedure for sequential detection of a change in a process mean.",
  "The detector behind our drift-triggered refit rule.",
  doi="10.2307/2333009"),
S("GAMA2014", "Gama, J.; Zliobaite, I.; Bifet, A.; Pechenizkiy, M.; Bouchachia, A.", 2014, "A Survey on Concept Drift Adaptation",
  "ACM Computing Surveys 46(4):44", "ML venue", "ML methods", 3,
  "Taxonomy of concept-drift detection and adaptation, including false-alarm control for sequential detectors.",
  "Source of the calibrate-then-freeze discipline we apply to the drift threshold.",
  doi="10.1145/2523813"),
]
